### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by matejc** [browsh-org/browsh#102]
Is there a way to get some sort of "official" build instructions to compile browsh from source, so that someone can package it for source based Linux distros, like NixOS. I could get the process from the travisci or build scripts.... I could also use a binary file from releases here on GitHub and then set interpreter with patchelf[1], but those things are far from ideal.

[1] Right now the static binary seg. faults because there is no linker in the /lib64 folder. NixOS does not have /lib64/ld-linux-x86-64.so.2 but there is a different path for each build of glibc (example: /nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib/ld-linux-x86-64.so.2), also the patchelf is throwing this: `patchelf: no section headers. The input file is probably a statically linked, self-decompressing binary`

**Comment by tombh** [comment]
I'm a little lost as to the patchelf problem. I think this might be a problem specific to Golang in general? Were you already aware that Browsh is compiled by Golang, not by gcc?

But this is just to do with the fact that I try to UPX compress all the binaries?

Anyway, yes I'm very happy to help however I can! Thank you.

**Comment by matejc** [comment]
If I understand correctly... you can also provide instructions for the whole process, along with the build process where you convert a Mozilla web extension, I think that this would be the optimal solution.

But if no, at least for Nix, uncompressed binary should work, I would need to get one to try it out...

**Comment by parkerlreed** [comment]
Yeah even just basic instructions on how to build would be nice. For example I want to test a fix for an issue but have been completely unable to get the build process working.

**Comment by tobimensch** [comment]
@tombh 
Detailed build instructions would be really nice. I imagine you would gain many contributors that way.

**Comment by tombh** [comment]
The fact is, not even I can build an official release of Browsh! :D The crux being that the Mozilla web extension must be built with a new version number or it's rejected by Mozilla. So the only way to make an official build is to do so after a version bump in the post commit hook of a Travis build.

However, for development purposes you can build the web extension with the `webext` tool (which is bundled with Browsh's development dependencies). For full instructions see: https://github.com/browsh-org/browsh#contributing

@matejc As of v1.4.0 I've disabled compression for all the binaries:  https://github.com/browsh-org/browsh/releases/tag/v1.4.0 If you want to include any automated NixOS-related hooks on version bumps, let me know, I'll be very happy to help.

**Comment by tombh** [comment]
There's now a single, reference script for building a production version of Browsh: https://github.com/browsh-org/browsh/blob/master/interfacer/contrib/build_browsh.sh

**Comment by davehouser1** [comment]
This script no longer works with newer versions of golang (go 1.19). I cant `go get` anymore. It must be `go install`

**Comment by tombh** [comment]
I'm pretty sure all the SETUP*.md docs are out of date now. Your best bet would be to follow the `Dockerfile` for now.
