### ISSUE TITLE
Dependency is not satisfiable: firefox on debian stretch

### ISSUE THREAD

**Issue by mancausoft** [browsh-org/browsh#103]
I can't install the deb file on debian:
Dependency is not satisfiable: firefox

on stretch  the package is called firefox-esr

**Comment by tobimensch** [comment]
I'm using official firefox nightly builds from mozilla on Debian Jessie with great success.

You should try it.

**Comment by azzamsa** [comment]
Have same issue here. I installed firefox in Debian 9 in /opt/. But it already had symlink in /usr/bin.

apt can't detect installed firefox this way. So installing browse will produce this error

``` bash
$ dpkg -i browsh_1.2.3_linux_amd64.deb 
sudo dpkg -i browsh_1.2.3_linux_amd64.deb 
Selecting previously unselected package browsh.
(Reading database ... 358199 files and directories currently installed.)
Preparing to unpack browsh_1.2.3_linux_amd64.deb ...
Unpacking browsh (1.2.3) ...
dpkg: dependency problems prevent configuration of browsh:
 browsh depends on firefox; however:
  Package firefox is not installed.

dpkg: error processing package browsh (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 browsh
```

@tobimensch how did you install browsh ? how to make apt detect installed firefox ?

Thanks in advance

**Comment by azzamsa** [comment]
I think it should be 

>Make it executable:
>chmod +x browsh_1.2.3_linux_amd64

Thanks. works like a charm.

**Comment by tobimensch** [comment]
Doesn't matter. Either one works.

Happy it works for you!

**Comment by tombh** [comment]
I've pushed a fix for this. But unfortunately the fact is that `firefox-esr` is too old to run Browsh, at least Firefox 57 is needed.
