### ISSUE TITLE
Fedora 28 - Panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jonathan-91** [browsh-org/browsh#107]
![image](https://user-images.githubusercontent.com/8642945/42557303-6e22a760-84ee-11e8-987a-2a2e420a7e6d.png)

**Comment by Ovenwand** [comment]
Getting the same in Ubuntu 18.04

**Comment by shadeofgod** [comment]
I have the same error when trying to ssh to brow.sh, and after that once I move my mouse the prompt get messy codes.

![screen shot 2018-07-11 at 17 04 54](https://user-images.githubusercontent.com/18644268/42561840-bfbb7a1e-852c-11e8-9670-08f8e8eef704.png)

**Comment by tombh** [comment]
This was a careless mistake on my part. It's since been fixed in v1.3.2. You can immediately test this at `ssh brow.sh`.
