### ISSUE TITLE
feature request: adblocking

### ISSUE THREAD

**Issue by rynnon** [browsh-org/browsh#109]
I really miss an adblocker. IMO, it's necessary to use the web comfortably these days; other methods for blocking ads, while possible, are considerably more complicated to set up than a browser extension. In the context of browsh, ads are particularly confusing, since they break up the already so-so (compared to GUI browsers) site rendering.

If this is possible without too much work, I'd really like to see it as a feature.

**Comment by parkerlreed** [comment]
Alternatively: Run browsh with `-with-gui` and install extensions as you would normally

**Comment by rynnon** [comment]
Neat!
