### ISSUE TITLE
WSL (ubuntu 18.04) error

### ISSUE THREAD

**Issue by zyp001a** [browsh-org/browsh#110]
Windows Subsystem for Linux
▒/P2▒S_9▒▒▒``C▒@>*▒
                   ▒Np▒▒▒▒^?▒[@x▒▒      n_O▒r▒B`r▒ax3▒=q▒h▒@▒Xl▒_▒▒F▒▒: not found
/usr/local/bin/browsh: 6: /usr/local/bin/browsh: cannot create SGo▒▒UhtE8mQ42Ns6xnUjoncK/62tN1kLz0t▒▒▒▒dOLQV9xeoS/h93XZyGsdE77MrVGmsJ5/▒▒▒▒OgTEK9VT3x6P3gx4mZ/lib64: Directory nonexistent
/usr/local/bin/browsh: 6: /usr/local/bin/browsh: B▒: not found
/usr/local/bin/browsh: 7: /usr/local/bin/browsh: Syntax error: ")" unexpected
PuTTYPuTTYPuTTY

**Comment by DanielRuf** [comment]
This output is very unreadbable. Can you provide some screenshot or better readable output?

**Comment by corwin78** [comment]
Hello guys, I am found exactly the same issue - again Windows 10 64bit with Ubuntu 16.04 under Windows Subsystem for Linux. Please see attached screenshot.

![browsh-error](https://user-images.githubusercontent.com/354014/42569399-af39ab96-8510-11e8-9739-b98c87c07a24.png)

**Comment by corwin78** [comment]
Anyway, it looks to me like wrong executable, not for AMD64, but Browsh has been installed from browsh_1.3.2_linux_amd64.deb.

**Comment by tombh** [comment]
Hmm, these errors are similar, I wonder if it's the fact that I use UPX to compress the files. If anyone's interested you can try to decompress the binary by installing UPX https://upx.github.io/ and running `upx -d` against the browsh binary in `/usr/local/bin`.

**Comment by corwin78** [comment]
Yes, it looks that UPX compression is the issue - decompressed file is working as it should.
I am found [this](https://github.com/upx/upx/issues/201) discussion on UPX github to this topic.
And [this](https://github.com/Microsoft/WSL/issues/330) is discussion on WSL github.

**Comment by tombh** [comment]
As of v1.4.0 all release binaries are uncompressed.
