### ISSUE TITLE
Windows: exec: "c:\\Program": file does not exist

### ISSUE THREAD

**Issue by jan-herout** [browsh-org/browsh#111]
Binary browsh_1.3.2_windows_386.exe does not run on my system (Windows 10).
STDERR contains "exec: "c:\\Program": file does not exist"

I suppose it might be related to Firefox installation to "c:\Program Files" ???

**Comment by DarthJahus** [comment]
It would be great to detect Firefox path. Maybe by reading the registry:

`HKEY_CURRENT_USER\Software\Mozilla\Mozilla Firefox`

Then read "CurrentVersion" variable (let it be `VERSION`)

Then open `HKEY_CURRENT_USER\Software\Mozilla\Mozilla Firefox\{VERSION}\Main\PathToExe`

That points directly to the Firefox binary.

**Comment by Aidoboy** [comment]
I used `.\browsh_1.3.2_windows_amd64.exe -firefox C:\Progra~1\Mozill~1\firefox.exe`

**Comment by Micro-BIOS** [comment]
With that command line I get:
Firefox binary not found in: c:\Program Files (x86)\Mozilla Firefox\firefox.exe or c:\Program Files\Mozilla Firefox\firefox.exe

which is clearly not true.

**Comment by zz0rk** [comment]
Copy browsh to root of firefox.exe then
.\browsh_1.3.2_windows_amd64.exe -firefox firefox.exe

**Comment by tombh** [comment]
As @Aidoboy points out you need to first know the location of your Firefox and then you need to pass that as an argument to `.\browsh_1.3.2_windows_amd64.exe -firefox <path to firefox>`.

However, Windows has other problems once you get past that. Please follow #78 to be updated.

**Comment by Aidoboy** [comment]
@tombh I don't know if this should necessarily be closed, automatically finding Firefox is still broken, and you have to know about the ~ path workaround, because the path can't have any spaces in it, even with quotes

**Comment by tombh** [comment]
@Aidoboy fair point. There's actually another issue about finding the Firefox path #130, is that ok?

**Comment by Aidoboy** [comment]
Hmm, maybe. I feel the main issue here is really "can't handle spaces at
all", though.
