### ISSUE TITLE
"character set not supported" on windows 10

### ISSUE THREAD

**Issue by funatsufumiya** [browsh-org/browsh#116]
```
.\browsh_1.3.2_windows_amd64.exe
character set not supported
```

**Comment by Nadav-Ruskin** [comment]
You're trying to use WSL. Open CMD.

**Comment by funatsufumiya** [comment]
@Nadav-Ruskin 
No, I tried this on cmd and powershell. But nothing worked.

**Comment by tombh** [comment]
What about cmder or ConEmu?

**Comment by ttma1046** [comment]
same error on comder.

`character set not supported`

**Comment by ttma1046** [comment]
I am using Windows 7. 
My case is 'character set not supported' doesn't show on CMD but on cmder, but memory leak error on cmd.

Already get Browsh working on my Mac.

Thanks so much!

**Comment by tombh** [comment]
Hmm, yeah that memory leap problem is one I've seen too. But glad you got it working on Mac!

**Comment by AgentConDier** [comment]
This is really weird. At first, I got this when running from CMD, GitBash or PowerShell. Then it suddenly started working for CMD and PowerShell. But if I ssh into Windows, it prints `character set not supported` again.
