### ISSUE TITLE
Using browsh with firefox based browser....

### ISSUE THREAD

**Issue by furycd001** [browsh-org/browsh#118]
HI

Is it possible to use browsh with a firefox based browser like waterfox or pale moon ?? I currently use waterfox and would like to be able to use browsh without having to install firefox. Could I point browsh to my waterfox install ??

Many thanks.
Jonny....

**Comment by parkerlreed** [comment]
Everything I see points to Waterfox being on 56. It's not new enough for browsh to work with it. Once it hits 57 you'll most likely be able to point it to Waterfox and it will work.

**Comment by furycd001** [comment]
Thanks for the heads up :)
