### ISSUE TITLE
ver 1.3.3: does not do anything, it stays at "waiting for firefox to connect"

### ISSUE THREAD

**Issue by osmand** [browsh-org/browsh#123]
What do you want to know?

Control-Q works and it exits clean.

Attempting to connect to Firefox Marionette
Starting Firefox in headless mode
Using default profile at: /home/x/.config/browsh/firefox_profile
FF-CONSOLE: 1531382485743	Marionette	INFO	Listening on port 2828
FF-MRNT: 50:{"applicationType":"gecko","marionetteProtocol":3}
Sending `newSession` to Firefox Marionette
FF-MRNT: 521:[1,0,null,{"sessionId":"754d7aad-ce09-4208-9794-2a14163a133e","capabilities":{"browserName":"firefox","browserVersion":"61.0","platformName":"linux","platformVersion":"4.13.0-45-generic","pageLoadStrategy":"normal","acceptInsecureCerts":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"moz:accessibilityChecks":false,"moz:headless":true,"moz:processID":9759,"moz:profile":"/home/x/.config/browsh/firefox_profile","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 13:[1,1,null,{}]
Sending `executeScript` to Firefox Marionette
FF-MRNT: 25:[1,2,null,{"value":null}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 13:[1,3,null,{}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 13:[1,4,null,{}]
Sending `executeScript` to Firefox Marionette
FF-MRNT: 25:[1,5,null,{"value":null}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 13:[1,6,null,{}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 13:[1,7,null,{}]
Sending `executeScript` to Firefox Marionette
FF-MRNT: 25:[1,8,null,{"value":null}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 13:[1,9,null,{}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,10,null,{}]
Sending `executeScript` to Firefox Marionette
FF-MRNT: 26:[1,11,null,{"value":null}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,12,null,{}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,13,null,{}]
Sending `executeScript` to Firefox Marionette
FF-MRNT: 26:[1,14,null,{"value":null}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,15,null,{}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,16,null,{}]
Sending `executeScript` to Firefox Marionette
FF-MRNT: 26:[1,17,null,{"value":null}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,18,null,{}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,19,null,{}]
Sending `executeScript` to Firefox Marionette
FF-MRNT: 26:[1,20,null,{"value":null}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,21,null,{}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,22,null,{}]
Sending `executeScript` to Firefox Marionette
FF-MRNT: 26:[1,23,null,{"value":null}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,24,null,{}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,25,null,{}]
Sending `executeScript` to Firefox Marionette
FF-MRNT: 26:[1,26,null,{"value":null}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,27,null,{}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,28,null,{}]
Sending `executeScript` to Firefox Marionette
FF-MRNT: 26:[1,29,null,{"value":null}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,30,null,{}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,31,null,{}]
Sending `executeScript` to Firefox Marionette
FF-MRNT: 26:[1,32,null,{"value":null}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,33,null,{}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,34,null,{}]
Sending `executeScript` to Firefox Marionette
FF-MRNT: 26:[1,35,null,{"value":null}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,36,null,{}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,37,null,{}]
Sending `executeScript` to Firefox Marionette
FF-MRNT: 26:[1,38,null,{"value":null}]
Sending `setContext` to Firefox Marionette
FF-MRNT: 14:[1,39,null,{}]
Sending `addon:install` to Firefox Marionette
FF-MRNT: 62:[1,40,null,{"value":"{8ff2d753-2dc8-46de-a837-fa28331d9fcf}"}]
Starting Browsh CLI client
Webextension not connected. Message not sent: /tty_size,80,42
Sending `quitApplication` to Firefox Marionette
FF-MRNT: 32:[1,41,null,{"cause":"shutdown"}]
*errors.errorString normal
/home/travis/gopath/src/browsh/interfacer/src/browsh/tty.go:95 (0x6deb57)
/home/travis/gopath/src/browsh/interfacer/src/browsh/tty.go:54 (0x6deb02)
/home/travis/gopath/src/browsh/interfacer/src/browsh/tty.go:42 (0x6de8d9)
/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/runtime/asm_amd64.s:2361 (0x457541)

**Comment by tombh** [comment]
This is hard problem to debug I'm afraid. Others have reported similar issues. The only thing I can recommend is to make sure all of your Firefox processes are killed. And then try again.

**Comment by tombh** [comment]
Closing as there's not been any new updates in a while.
