### ISSUE TITLE
question: can you do what browsh does with php?

### ISSUE THREAD

**Issue by osmand** [browsh-org/browsh#125]
Then I would be able to contribute :)

How would one access firefox with php ?

**Comment by joereynolds** [comment]
I doubt the devs have any plans to re-write this in php but you can look into the `exec` or `shell_exec` functions for php.

**Comment by tobimensch** [comment]
@osmand 
I think it's much easier to learn JS and Go than you imagine. Like php those are basically imperative programming languages. You can pick up the syntax quickly and the API is well documented.

browsh's code is fairly well commented and cleanly written, so it ought to be a decent starting point for learning JS and Go simultaneously.

Don't be afraid and I'm quite certain you can contribute a lot in just a matter of weeks.

**Comment by tombh** [comment]
As @tobimensch says, JS and Golang really aren't that hard to learn, especially if you have some PHP experience already. Give it a go!
