### ISSUE TITLE
How to use the http server for remote browsing in the terminal?

### ISSUE THREAD

**Issue by Siilwyn** [browsh-org/browsh#129]
Reading through the docs I got the http server working, I can access it on my browser but that way it does not have feature parity with terminal rendering, right?

So I'm wondering how to use the http service through SSH like it's intended?

**Comment by tombh** [comment]
Well to use all of Browsh's features, you just need to run Browsh normally, without any arguments at all. If you install Browsh on a remote VM, then you'll already be SSH'd in so you can Browse the web straight away.

**Comment by Siilwyn** [comment]
Aha, got it, thank you for your reply!
