### ISSUE TITLE
Automatically detect Firefox path on Windows

### ISSUE THREAD

**Issue by DarthJahus** [browsh-org/browsh#130]
It would be great to detect Firefox path. Maybe by reading the registry:

`HKEY_CURRENT_USER\Software\Mozilla\Mozilla Firefox`

Then read "CurrentVersion" variable (let it be `VERSION`)

Then open `"HKEY_CURRENT_USER\Software\Mozilla\Mozilla Firefox\" + VERSION + "\Main\PathToExe"`

That points _directly_ to the Firefox binary.

ref. #111 

Edit: Formatting.

**Comment by tobimensch** [comment]
Good idea.

**Comment by tombh** [comment]
Thanks very much for this idea. It's has been implemented since v1.4.5
