### ISSUE TITLE
please make an aur of this. thx!

### ISSUE THREAD

**Issue by Im-Nameless** [browsh-org/browsh#131]
I would love to be able to install it trough the aur. it would help greatly. thx.

**Comment by lodi-g** [comment]
`aur/browsh-bin`

https://aur.archlinux.org/packages/browsh-bin/

**Comment by tombh** [comment]
Awesome!

So what happens when a new version is released? Do you have to upload the package again? Is there something I can do to help automate this?

**Comment by lodi-g** [comment]
It is maintained manually by a user whose nickname is MikuroK.

From what I see you could help maintain it by updating the release URL and sha512sum in the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=browsh-bin).

If you're not familiar with how the AUR works, I suggest reading [Arch User Repository
](https://wiki.archlinux.org/index.php/Arch_User_Repository).

**Comment by giuscri** [comment]
To the best of my knowledge, people can only flag a package out-of-date but it's maintainer's responsibility to update it. An alternative would be writing the `browsh-git` package.

**Comment by tombh** [comment]
Well the thing is that I already have lots of post release hooks doing various things when a Browsh's version gets bumped, so they might as well automatically update the AUR whilst they're at it. I'll see if I can collaborate with MikuroK, or just add my own.

**Comment by tombh** [comment]
Closing as https://aur.archlinux.org/packages/browsh-bin/ solves this
