### ISSUE TITLE
Anchor link is not clickable if it contains block elements

### ISSUE THREAD

**Issue by kevinsimper** [browsh-org/browsh#132]
If a `<a>` tag contains `display: block` elements, it is not shown as clickable links. In html5 it is allowed to put block elements inside anchor links, which was not allowed in html4. https://stackoverflow.com/a/1828032

Thanks for the awesome software! <3

**Comment by tombh** [comment]
Thanks for reporting this! Do you happen to have a URL with such a problematic `<a>` in it?

Thanks <3

**Comment by kevinsimper** [comment]
Yes, here is a demo, 

https://html.brow.sh/https://output.jsbin.com/vadevumohu

https://jsbin.com/vadevumohu/edit?html,output

**Comment by tombh** [comment]
Accidentally closed this with the wrong issue number in the commit.

**Comment by j-rewerts** [comment]
I can't seem to reproduce this. @kevinsimper Are you still experiencing this issue?

**Comment by kevinsimper** [comment]
@j-rewerts It is still a issue, see here https://html.brow.sh/https://output.jsbin.com/nivapeliza

**Comment by tombh** [comment]
Gosh, there's quite a few rendering issues with that link actually!

**Comment by kevinsimper** [comment]
@tombh Is there something I can do to help? 😄 💛
