### ISSUE TITLE
Don't use google.com as home page as Browsh won't load if Google is blocked

### ISSUE THREAD

**Issue by xplorld** [browsh-org/browsh#136]
```
docker run --rm -it browsh/browsh
```
![image](https://user-images.githubusercontent.com/7023694/42743573-b83147dc-88f7-11e8-89e3-597ee197b2ad.png)
And it waits forever.

**Comment by ThyrixYang** [comment]
I encountered the same error.

**Comment by ThyrixYang** [comment]
This may because google is blocked in your area, google is the default home page.
I fixed it by changing to baidu.

**Comment by tobimensch** [comment]
@tombh 
Seems like it could be fixed by testing if the startup URL is reachable and by falling back to another URL (maybe even brow.sh) if necessary.

**Comment by tombh** [comment]
Wow! Excellent detective work @ThyrixYang. I don't know how you figured that out, you must have done a lot of digging into the logs and code. Thank you very much for taking the time to do that.  你是中国人吗？我现在在昆明。我学习中文十个月！

So yeah, I agree @tobimensch, I'll set the homepage to brow.sh. It's the most relevant and universally accessible (at the moment!) site for us.

**Comment by ThyrixYang** [comment]
@tombh Yes! 我在南京大学读书，很高兴现在学习中文的外国人越来越多了.
I just guessed this probability as I'm always dealing with such problems...
And cheer for your excellent browsh ;)

**Comment by tombh** [comment]
你猜好了！很聪明
越来越多。 加油！

So I'll close this once I've changed the URL for the default homepage.

**Comment by tombh** [comment]
Fixed in v1.4.7
