### ISSUE TITLE
debian repo?

### ISSUE THREAD

**Issue by lucapaganotti** [browsh-org/browsh#139]
Hi guys, not an issue at all, but as you publish .deb packages I'm wondering if there exists a package repository I can setup on my debian box, just to have auto-updates. Thanks :-)

**Comment by tobimensch** [comment]
I don't think so. Maybe you could make a request for debian packagers to add Browsh to an official debian repository.

**Comment by tobimensch** [comment]
@lucapaganotti 
Install the reportbug tool for debian. Then file a RFP (request for package) bug.

**Comment by tobimensch** [comment]
Support for firefox 52 runs out on the 5th of September. Which means that firefox-esr 60 will land in Debian Stretch soon thereafter.
That should make official debian packages possible.

**Comment by lucapaganotti** [comment]
Hi, thank you all, I've submitted an RFP with reportbug, if firefox will be
updated in september or earlier I can wait ;-)

----------------------------------------------------------------
-- Dott. Ing. Luca Paganotti
-- Via dei Giardini 9
-- 21035 Cunardo (VA)
-- 393 1346898
----------------------------------------------------------------
-- softech s.r.l. email:
-- luca.paganotti@softechweb.it
-- luca.paganotti@gmail.com
-- https://github.com/lucapaganotti
-- sourceforge email:
-- lucapaganotti@users.sourceforge.net
-- skype name: luca.paganotti
[image: http://it.linkedin.com/in/lucapaganotti]
<http://it.linkedin.com/in/lucapaganotti>
-- https://www.facebook.com/luca.paganotti.66
-- ---------------------------------------------------------------
-- Mistakes are portals of discovery - JAAJ
--- --------------------------------------------------------------

**Comment by tobimensch** [comment]
Nice, I'm closing the issue for now.
