### ISSUE TITLE
Add Mosh to Dockerfile

### ISSUE THREAD

**Issue by niutech** [browsh-org/browsh#140]
The SSH rendering is very slow, so please add Mosh server alongside SSH daemon to the Dockerfile.

**Comment by tombh** [comment]
Are you looking at this [Dockerfile](https://github.com/browsh-org/browsh/blob/dcc3cb0f1eb36617b25367df17811831879ed16a/Dockerfile)? There's no SSH daemon in there. It's really just a wrapper for `browsh` itself. The idea is that you install it on a remote VM that you can connect to independently of Browsh. Mosh is really just a better version of SSH, it does pretty much exactly the same thing. I've actually recently added some documentation about Mosh: https://www.brow.sh/docs/mosh/

**Comment by niutech** [comment]
Yes, I have installed Mosh next to Docker in my VPS, then connected to it using `mosh user@myserver` and then executed `docker run -it browsh/browsh`.

**Comment by tombh** [comment]
Great! So you're all good now?

**Comment by niutech** [comment]
Yes, I can run browsh through mosh.

**Comment by klihelp** [comment]
@niutech could you share to the audience how you "connected" the docker images and run browsh through mosh?

**Comment by niutech** [comment]
@klihelp I have described it in the [comment above](https://github.com/browsh-org/browsh/issues/140#issuecomment-405952994).
