### ISSUE TITLE
Not running on mac

### ISSUE THREAD

**Issue by NickRaleigh** [browsh-org/browsh#141]
Returns signal: segmentation fault

**Comment by tombh** [comment]
Haha. I really need to add an issue template to remind users to add more context to bug reports :D

Can you try again but add the debug flag (pre v1.4.0 use `-debug`, post v1.4.0`--debug`). And then paste the output of `./debug.log`. Also would be good to know the Browsh version you're using and whether it's in Docker.

**Comment by mandarvaze** [comment]
I installed version 1.4.6 using homebrew, and it works well (inside iTerm2)
I'm on macOS Sierra - if it matters.

**Comment by tombh** [comment]
Closing as there's been no new info in a while.
