### ISSUE TITLE
Try to fix readme

### ISSUE THREAD

**Issue by Hanrisxie94** [browsh-org/browsh#143]

**Comment by tobimensch** [comment]
What exactly should be fixed? I think I must close this unless you can explain in what way it ought to be fixed.

**Comment by tombh** [comment]
What happened here?

**Comment by tobimensch** [comment]
@tombh 
First I thought we can close this issue, unless @Hanrisxie94 provides more info. Upon further thought I figured he's probably right, the README could be a lot better still.
Seeing how it's the first thing people read when they visit here, it's seems important to perfect it.

@Hanrisxie94 
Can you please expand on this issue? In what way does it need fixing? What did you miss in there? What should be changed?

**Comment by awilfox** [comment]
The major thing I noticed missing from the README was that there's no build instructions.

My main workstation is a 64-bit PowerPC computer (a Talos II).  I can't run x86_64 binaries, and Docker doesn't work right on this architecture.  I don't exactly grok what the Dockerfile is doing (I have no experience with Docker nor do I want any).  There's not even a build system that I can discern.

**Comment by awilfox** [comment]
Yes!  Thank you very much.

**Comment by tombh** [comment]
Great. I'll close this for now. But let me know if you have any problems.
