### ISSUE TITLE
portable firefox

### ISSUE THREAD

**Issue by winnoryder** [browsh-org/browsh#145]
I have portable firefox,how to use browsh on portable veision?

**Comment by tobimensch** [comment]
I'm assuming you just point browsh to the portable firefox binary?
browsh -firefox path/to/binary

**Comment by tobimensch** [comment]
@winnoryder 
Did you get around to try it?

**Comment by winnoryder** [comment]
sorry，i didn't try it, I get plugin version in my firefox

**Comment by tombh** [comment]
Closing this as it looks like the solution has already been given.
