### ISSUE TITLE
Use framebuffer in TTY mode, like "links".

### ISSUE THREAD

**Issue by mikedebian** [browsh-org/browsh#148]
Links is able to show webpages as they would be presented in X, using framebuffer (dev/fb0).

I notice that browsh has the issue under TTY to render pages correctly, without every second row being black.

As far as I know, links uses framebuffer and is able to show webpages using true color in TTY via the framebuffer.

For example, here is an image of the web browser "netsurf" using framebuffer, without X (tty)

[Image](https://forum.manjaro.org/uploads/default/original/3X/b/8/b82339f284091a15d90b3f46de0593bb9dec8481.png)

**Comment by parkerlreed** [comment]
Framebuffer is a whole other can of worms. The old DirectFB methods are way outdated, and newer KMS/DRM methods are GPU dependent. 

Besides if you are going to do KMS/DRM you could display the full browsing experience at that point and not need the text mode.

Would be neat to see if it could be done, but it feels like that's the complete opposite of what browsh is trying to be. Minimal.

**Comment by tombh** [comment]
Sorry to be brief, but I've already discussed this a few times in various issues. I'm going to defer this to #137
