### ISSUE TITLE
Upgrade to stable and latest nodejs

### ISSUE THREAD

**Issue by doronbehar** [browsh-org/browsh#149]
I was just wondering, what's holding Browsh from using the latest stable `nodejs` version `10.7.0`?

**Comment by tombh** [comment]
Absolutely nothing! Should be easy to upgrade, I've got lots of tests to make sure everything will still work. I'll have this done (and Golang) upgraded for the next release. Thanks.

**Comment by trantata** [comment]
Tải Outlook for iOS
	





On Tue, Jul 24, 2018 at 11:39 PM +0700, "Doron Behar" <notifications@github.com> wrote:












I was just wondering, what's holding Browsh from using the latest stable nodejs version 10.7.0?

**Comment by trantata** [comment]
Tải Outlook for iOS
	





On Fri, Jul 27, 2018 at 12:20 PM +0700, "Thomas Buckley-Houston" <notifications@github.com> wrote:












Closed #149 via 39da787.

**Comment by tombh** [comment]
Always good to hear from you @trantata :rofl:
