### ISSUE TITLE
Is there any way to click on a link with the keyboard?

### ISSUE THREAD

**Issue by battaglia01** [browsh-org/browsh#152]
Right now in browsh 1.4.8, I can follow links by clicking on them with the mouse. Can I follow them with the keyboard somehow? Is it possible to use browsh without having a mouse?

**Comment by tobimensch** [comment]
This is being discussed in #31 . I'm sure this will soon be implemented, but to answer your question, in 1.4.8 there's no way to click on links using the keyboard. However there was someone who reported some success using the vim vixen extension. I'm not sure to what extend you can use the keyboard for navigation with that extension.

**Comment by tobimensch** [comment]
Check out the vim-mode-experimental branch.
