### ISSUE TITLE
version 1.4.9 fails to start: "open /browsh.xpi: file does not exist"

### ISSUE THREAD

**Issue by grahamlopez** [browsh-org/browsh#155]
I'm on ubuntu 18.04 using gnome-terminal, and when I installed the release 1.4.9 .deb, browsh will not start, giving the message `open /browsh.xpi: file does not exist`

On a subsequent try, I get "A headless Firefox is already running"

version 1.4.8 works fine. I've attached my debug.log

[debug.log](https://github.com/browsh-org/browsh/files/2233036/debug.log)

**Comment by pca2** [comment]
Ditto on Xubuntu 16.04

**Comment by MikuroK** [comment]
In my effort to make an AUR package, I ran into this error myself. It occurs when go-bindata is given a different path between the -prefix, and the source binary (the webextension in this case).
checking out unstripped strings in the 1.4.9 release binary, it appears the xpi was sourced from "/home/travis/gopath/src/browsh/webext/dist/web-ext-artifacts/browsh.xpi", but the xpi2bin.sh script uses the interfacer directory as the prefix to strip, which in this case is "/home/travis/gopath/src/browsh/interfacer".
