### ISSUE TITLE
Cannot launch browsh

### ISSUE THREAD

**Issue by yotama9** [browsh-org/browsh#156]
Hi, 

I just installed the 1.4.9 amd64 pacakge on Ubuntu 18.04. When I type in terminal ``browsh`` I get a blank screen for a second or two, and then I'm back in terminal with a message   

    open /browsh.xpi: file does not exist

If now I try again, I immediately get a message 

    A headless Firefox is already running 

How can I solve this?

**Comment by tobimensch** [comment]
This should be solved in 1.4.10, which is currently being released.

**Comment by mandaputtra** [comment]
Happening on Ubuntu 20.04
