### ISSUE TITLE
Possible trojan?

### ISSUE THREAD

**Issue by Some-T** [browsh-org/browsh#158]
Sorry, if I duplicated this, might be that it did'nt go through on my other post so here it is again.

I was trying this out in Windows to see if I could get it working, I could not.

I decided to scan the file: https://github.com/browsh-org/browsh/releases/download/v1.4.10/browsh_1.4.10_windows_amd64.exe at https://www.virustotal.com/#/home/upload however it produced this:

[![Screenshot from Gyazo](https://gyazo.com/b2510770f2475e95af63c30a41e8fd64/raw)](https://gyazo.com/b2510770f2475e95af63c30a41e8fd64)

Can anyone confirm if this is a false positive or not please?

**Comment by tobimensch** [comment]
I'm certain it's a false positive.

**Comment by Some-T** [comment]
Thanks, yeah I thought so, doing a search on the Gorsh.a backdoor does not bring up many results. If you or anyone else has evidence or developer insight just so I can be 110% certain would be much appreciated.

**Comment by tombh** [comment]
Theoretically all binaries are completely auditable. The source code is public, you can see that here. You can match the commit SHAs to Travis builds at https://travis-ci.org/browsh-org/ And you can match all the checksums from eg; https://github.com/browsh-org/browsh/releases
