### ISSUE TITLE
Tilix has black string

### ISSUE THREAD

**Issue by zyf0330** [browsh-org/browsh#159]
I use Tilix, it should support true color , but browsh shows this.
![image](https://user-images.githubusercontent.com/11958657/43378750-5a204256-93fb-11e8-95e7-30ce75ad8b00.png)
[debug.log](https://github.com/browsh-org/browsh/files/2239760/debug.log)

**Comment by tobimensch** [comment]
This looks like #77 . There @jyapayne has found a solution https://github.com/browsh-org/browsh/issues/77#issuecomment-406455937

Please try this solution and if it's not working you can reopen this issue.

**Comment by tobimensch** [comment]
I'm quoting @jyapayne:

"After deleting lines in my bashrc to see if anything changes, the offending line is this one:

export LANG="ja_JP.UTF-8"
"

**Comment by zyf0330** [comment]
I haven't set this, and unset LANG is useless.
I use firefox v61 too.

**Comment by tobimensch** [comment]
Okay, I'm reopening your issue.

Just curious, did you try it with other terminals, too?

**Comment by zyf0330** [comment]
I tried with Terminator, Yakuka, they have the same problem.

**Comment by tobimensch** [comment]
Could you try it with gnome-terminal or konsole, too?

**Comment by tombh** [comment]
I'm imagining `LANG` might be being set elsewhere? Can you paste the output of running `env` on your CLI. Or at least `echo $LANG`. Thanks.

**Comment by zyf0330** [comment]
Actually I set `LANG` as my personal choice, not in bashrc but in system settings, but I have unset it before `browsh`.

**Comment by tombh** [comment]
Can you still just try those commands I suggested?

Also any "character set" settings set in your terminals. Thanks.

**Comment by zyf0330** [comment]
Ok, I will try tomorrow. Thanks.

**Comment by zyf0330** [comment]
I find that I set `LC_CTYPE` to other value too, and after unset it, browsh works normally.
So maybe browsh doesn't support "character set" settings other than en_US, I guess.

**Comment by zyf0330** [comment]
find that I set `LC_CTYPE` to other value too, and after unset it, browsh works normally.
So maybe browsh doesn't support "character set" settings other than en_US, I guess.

**Comment by zyf0330** [comment]
find that I set `LC_CTYPE` to other value too, and after unset it, browsh works normally.
So maybe browsh doesn't support "character set" settings other than en_US, I guess.

**Comment by tombh** [comment]
I think it's that Browsh doesn't support charcater sets that have wide characters, like Chinese and Japanese. Glad you fixed it. Thanks for trying, it will help other people with similar problems in the future.

**Comment by zyf0330** [comment]
When enter some Chinese chars, you will find some chars not showing.

**Comment by tombh** [comment]
See #75 to follow progress on support for all character sets like Chinese
