### ISSUE TITLE
build_browsh.sh isn't portable

### ISSUE THREAD

**Issue by vext01** [browsh-org/browsh#172]
Hi,

This is an extension of the discussion in #126 where we were discussing build instructions.

Thanks for writing the build script. I only looked briefly so far, but there's a few portability problems off the bat:

 * `readlink -m` isn't portable.
 * `bash` isn't guaranteed to be at `/bin/bash` (on my machine it's `/usr/local/bin/bash`), which makes shebangs on scripts fail.

The latter can be fixed (as long as you don't want to pass any flags to bash) with:

```
#!/usr/bin/env bash
```

Or, if you don't use any bash-specifics, you can simply use:

```
#!/bin/sh
```

Which will work for 99.9% of systems, bar Android, which I doubt you'd want to run browsh on anyway.

Cheers

**Comment by tobimensch** [comment]
If you make a pull request that makes the build script more portable, I'd be happy to merge it.

**Comment by j-rewerts** [comment]
#174 could help alleviate some of these issues. Maybe we could run build_browsh.sh inside a container?

**Comment by tombh** [comment]
@vext01 I didn't know that about `readlink`, thanks.

Agreed PRs certainly welcome.

Building in Docker is certainly possible, but a lot of build systems don't support it, like NixOS, see #102

**Comment by tobimensch** [comment]
@j-rewerts 
Don't really have an opinion. Just want to thank you for investigating this.

**Comment by tombh** [comment]
Yeah, thanks for looking into this.

Well we already use Go's `dep`, you can see all the dependencies listed in `interfacer/Gopkg.lock`. And the basic instructions for setting it up are in the contributing section of the README, although as you say, those instructions could be improved.

**Comment by j-rewerts** [comment]
Working on this now.

**Comment by j-rewerts** [comment]
My current approach may break symlinks. Any users in our community symlink the interfacer into their $GOPATH/src?
