### ISSUE TITLE
Browsh crashing with invalid memory address or nil pointer dereference on Ubuntu Touch

### ISSUE THREAD

**Issue by jonnius** [browsh-org/browsh#173]
Browsh crashes for me on Ubuntu Touch 16.04 (deb package installed). 
When running browsh via the Ubuntu Touch terminal or in a SSH session from my notebook with Ubuntu 16.04 and GNOME terminal, I get:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc2dc4]

goroutine 9 [running]:
os.(*Process).signal(0x0, 0x4e2078, 0x6a0110, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec_unix.go:56 +0x20
os.(*Process).Signal(0x0, 0x4e2078, 0x6a0110, 0xc, 0x11a01ce0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec.go:129 +0x2c
os.(*Process).kill(0x0, 0x11a01cf4, 0x11a4ef24)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec_posix.go:54 +0x34
os.(*Process).Kill(0x0, 0x4, 0x4)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec.go:114 +0x1c
browsh/interfacer/src/browsh.startHeadlessFirefox()
	/home/travis/gopath/src/browsh/interfacer/src/browsh/firefox.go:85 +0x2cc
created by browsh/interfacer/src/browsh.setupFirefox
	/home/travis/gopath/src/browsh/interfacer/src/browsh/firefox.go:288 +0x24
```
Running browsh directly via `phablet@IP browsh` I get 
```
open /dev/tty: no such device or address
```
Any idea?

**Comment by tombh** [comment]
Hmm, I don't have many ideas I'm afraid :/ You definitely have Firefox installed right?

Also, I don't completely understand what you're doing with `phablet@IP browsh`, can you give a few more details, thank you.

**Comment by jonnius** [comment]
Maybe it is the old kernel?

**Comment by tobimensch** [comment]
@jonnius 
Try running browsh in http-server mode.

**Comment by jonnius** [comment]
http-sever-mode gives me the same error.

**Comment by tombh** [comment]
I just had a quick look at what Ubuntu touch actually is. I suspect that there must be some limitation, whether in the OS or just the devices resources that prevent either the Browsh binary or headless Firefox from launching properly. The kernel should be a problem.

Anyway, the point is that the Browsh runtime is not meant to be installed on local devices, it should be installed and run remotely, either on a powerful desktop with good internet or on a remote VM. Then you can use Ubuntu Touch simply as a simple SSH (or better Mosh) client.

**Comment by jonnius** [comment]
Maybe the old kernel is the problem. Using it via ssh works, sure.

**Comment by tobimensch** [comment]
@jonnius 
I don't think the kernel version is the issue. I'm running Browsh on an OpenVZ-Server, which is based on kernel version  2.6.32, that is probably much older than your kernel.

**Comment by nicolasbd** [comment]
I have the same issue on mac os 10.11.6 "El Capitan" default terminal

**Comment by lomacks** [comment]
I have the same issue on a Raspberry Pi 3 running Raspbian 9. Any suggestions would be appreciated.

```
$ uname -a
Linux testpi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
$ firefox-esr --version
Mozilla Firefox 60.6.1
```

**Comment by lomacks** [comment]
In fact this is probably related to this in my case: https://raspberrypi.stackexchange.com/questions/75463/firefox-57-on-a-raspberry-pi

**Comment by tombh** [comment]
@lomacks The OP actually posted 2 different things, `invalid memory address` and `open /dev/tty: no such device or address`, which one do you have?

**Comment by Ccode-lang** [comment]
I have the exact same error message on minimal ubuntu (newest not LTS)

**Comment by jonnius** [comment]
I just tried once more on a FP4 with Ubuntu Touch 20.04 and I don't get a crash anymore.

**Comment by kiurious** [comment]
Hello,

Anyone managed to solve this? 
I am getting the same error, tried running it with the --firefox.use-existing flag to no avail.

--debug isn't giving me much of a lead: 
```bash
│❯ cat debug.log                                                                                                                                                                                                                                                     │
│Looking in /home/kiurious/.config/browsh/config.toml for config.                                                                                                                                                                                                    │
│Attempting to connect to Firefox Marionette                                                                                                                                                                                                                         │
│Starting Firefox in headless mode                                                                                                                                                                                                                                   │
│Using Firefox at: /usr/bin/firefox                                                                                                                                                                                                                                  │
│Using default profile at: /home/kiurious/.config/browsh/firefox_profile 
```
Firefox Version: 135.0
Go Version:  go1.23.3 linux/amd64  
Browsh Version: 1.8.2

Error: 
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4bbb19]

goroutine 6 [running]:
os.(*Process).signal(0x4a?, {0x94f8f8?, 0xb1bd30?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/os/exec_unix.go:63 +0x39
os.(*Process).Signal(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/os/exec.go:138
os.(*Process).kill(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/os/exec_posix.go:67
os.(*Process).Kill(0xc0002dc000?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/os/exec.go:123 +0x27
github.com/browsh-org/browsh/interfacer/src/browsh.startHeadlessFirefox()
        /home/runner/work/browsh/browsh/interfacer/src/browsh/firefox.go:92 +0x4ad
created by github.com/browsh-org/browsh/interfacer/src/browsh.setupFirefox
        /home/runner/work/browsh/browsh/interfacer/src/browsh/firefox.go:303 +0x25
```
