### ISSUE TITLE
Docker-based development environment

### ISSUE THREAD

**Issue by j-rewerts** [browsh-org/browsh#174]
Is there any interest in developing inside Docker containers? Could make standing up the dev environment easier for contributors that are familiar with Docker. If people are interested, I could look into this.

**Comment by tobimensch** [comment]
Contribute in whatever way you feel is a valuable use of your time. I've no experience with docker. I assume this could be useful for many people. Just go ahead and do it.

**Comment by scousetim** [comment]
-- 
null

**Comment by tombh** [comment]
Mr Reweeeeeeeeeeeeeeeeeeerts! Welcome :) Glad to you have you involved.

I've been thinking about this and I'm not sure how practical it would be. So let's say that you can just easily download a ready setup dev environment. Then you would SSH into it for example? But it wouldn't have your preferred editor in there, or your git setup?

You could certainly mount the filesystem from outside the container, but then that's going to get really tricky merging the `node_modules` and other automatically generated folders.

I think the best bet is just to improve the current [contributing docs](https://github.com/browsh-org/browsh#contributing).

**Comment by j-rewerts** [comment]
Happy to help!
Usually you use volume mounting to mount your source code into the container. I've never done it with Go before, but I've done it with .NET Core and Js/Node/Vue before. For Node, the volume included node_modules, which I feel kind of loses a lot of the benefit of using containers, so maybe there's a better way?
The other thing that would be crappy is you wouldn't actually have access to the firefox UI. With some of the work being done on installing add-ons for Brow.sh right now, that would make it a little tricky.
Overall, I think you're right. Probably could be done, but it might be too much work for now. Let me know if there is interest in the future!
I'll work on updating the contributing docs tonight hopefully.
