### ISSUE TITLE
Missing Chinese characters

### ISSUE THREAD

**Issue by yjchen** [browsh-org/browsh#175]
I tried html.brow.sh and text.brow.sh and found that some Chinese characters are not displayed correctly or missing. I assume it is a problem of fonts which do not contain all the unicode characters or some encoding issue. Here are the example:

https://html.brow.sh/https://zh.wikipedia.org/zh-tw/%E9%87%91%E9%97%A8%E5%85%AC%E5%9B%AD
https://text.brow.sh/https://zh.wikipedia.org/zh-tw/%E9%87%91%E9%97%A8%E5%85%AC%E5%9B%AD

The original page is https://zh.wikipedia.org/zh-tw/%E9%87%91%E9%97%A8%E5%85%AC%E5%9B%AD

**Comment by j-rewerts** [comment]
Is this related to #75? Notice [here](https://html.brow.sh/https://milankragujevic.com/vip-drop-i-lekcije-u-odnosu-sa-korisnicima) that the serbian is rendered strange.

**Comment by tombh** [comment]
It is indeed related, and in fact a duplicate. I'm actually quite close to fixing it, see here: https://github.com/fontforge/fontforge/issues/3322
