### ISSUE TITLE
Update Brow.sh Installation Instructions

### ISSUE THREAD

**Issue by j-rewerts** [browsh-org/browsh#179]
Some users have been confused by the current install process. Maybe splitting the installation section up a little more and adding some more instructions could help?

**Comment by j-rewerts** [comment]
This is addressed in [this](https://github.com/browsh-org/www.brow.sh/pull/18) pull request.

**Comment by tombh** [comment]
Yes! I just merged that PR. Do you think there's anything else we can do to help?

**Comment by j-rewerts** [comment]
We've addressed that issue from last week were the Mac user didn't know how
to run it, so I think it's a step in the right direction.

Still a little worried some of the install instructions won't work, but I'm
hoping we will get community feedback on it.

I'll get one of my coworkers to take a look tomorrow and see what she
thinks.

**Comment by bclue** [comment]
I do think that information on how to install browsh could be expanded on/laid out in a way that’s a bit more intuitive to users.  Even a couple of simple changes like having a link on the Downloads page to the Installation documentation might make it more clear for people. If it would help, I can look into expanding and improving this area.

**Comment by j-rewerts** [comment]
That'd be awesome. Thanks!

**Comment by tombh** [comment]
Yes please, we'll very happily accept any improvements to docs!

**Comment by j-rewerts** [comment]
Closing. I think they're good for now.
