### ISSUE TITLE
It’s like this after installation.

### ISSUE THREAD

**Issue by zhuxiaoxi** [browsh-org/browsh#181]
![2018-08-13 20-04-50](https://user-images.githubusercontent.com/2098464/44030742-4e241c0e-9f34-11e8-8d95-56ee5838b29d.png)

**Comment by tobimensch** [comment]
See #77

**Comment by scousetim** [comment]
Tim1968

**Comment by DogLooksGood** [comment]
I met the same problem, and solution in #77 not work in my case.
my `LANG` is `en_US.UTF8`.
