### ISSUE TITLE
Many vertical stripes appear in rendered webpage

### ISSUE THREAD

**Issue by pbxqdown** [browsh-org/browsh#182]
Just a few points to consider before submitting a bug report:

  * Do a quick search for any existing issues describing your bug
  * Give a clear and concise description of what the bug is
     The webpage is not rendered correctly. Many vertical stripes appear.
      
![1](https://user-images.githubusercontent.com/6386150/44243423-db7d2680-a183-11e8-94bb-d4a39f99ca61.png)

  * Include the contents of your `./debug.log` generated with `browsh --debug`
    
[debug.log](https://github.com/browsh-org/browsh/files/2295698/debug.log)

  * Include your OS and terminal name
    Ubuntu18.04 Gnome 3.28 with Gnome terminal

**Comment by tobimensch** [comment]
It looks like this issue #77
