### ISSUE TITLE
Setting up dev environment requires xpi file

### ISSUE THREAD

**Issue by j-rewerts** [browsh-org/browsh#184]
Currently, setting up the development environment seems to require the XPI (firefox extension) file. [See here](https://github.com/browsh-org/browsh/blob/master/interfacer/src/browsh/firefox.go#L223). It would be great if we didn't rely on this for local development.

**Comment by j-rewerts** [comment]
I'll submit a PR with an update to the README for collaborators. Really, all you have to do is run build_browsh.sh.

**Comment by j-rewerts** [comment]
It looks like the documentation around Browsh's command line args is out of date as well. Specifically, -use-existing-firefox should be --firefox.use-existing.

**Comment by flxwu** [comment]
yep, agreed. Local setup is indeed quite tricky...

**Comment by flxwu** [comment]
Fixed 👍 @tombh

**Comment by tombh** [comment]
Awesome. Feel free to close issues as and when you please ;)
