### ISSUE TITLE
New guide on how to setup the build environment on a generic linux system

### ISSUE THREAD

**Issue by tobimensch** [browsh-org/browsh#193]
Take a look at this new guide on how to install a build environment for browsh on Linux:
https://github.com/browsh-org/browsh/blob/master/contrib/setup_linux_build_environment.md

I know it's rough around the edges.

The goal is that people can become browsh developers as fast as possible. In my case, I couldn't rely on the package manager of my server's distribution, as Debian Jessie is too old in order to offer the latest and greatest packages of go and firefox and the like.

Please look for errors in this document, or for ways to improve it.

I want it to get linked from the README.md's contributing section eventually.

**Comment by tombh** [comment]
This is great, I think you can link to it already. There are definitely a few little clarifications I could add, but I can't do that right now.

**Comment by tobimensch** [comment]
@tombh 
Thanks. The link is there now. Clarifications are very much welcomed.

**Comment by tobimensch** [comment]
@tombh 
I hope you'll add the few little clarifications at a later date. In the meantime I'm closing this issue.
