### ISSUE TITLE
Upload browsh to Debian 

### ISSUE THREAD

**Issue by sunweaver** [browsh-org/browsh#199]
Hi,

I am a Debian Developer and would like to bring your project to Debian. As you already offer .deb  builds, could you possibly share the debian/ folder from which you build the .deb files?

Also: is it possible to run browsh with the NodeJS modules found in Debian unstable? It would be cool to offer this browser in Debian, so I'd appreciate some help when questions arise. Ok?

Thanks+Greets,
Mike

**Comment by sunweaver** [comment]
Never mind, I just saw that someone else is already working on this on the Debian side:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=904132

**Comment by tobimensch** [comment]
@sunweaver 
I've seen this Debian bug, but I can't quite figure out its status. Seems like someone closed it prematurely and then it was opened again?

**Comment by sunweaver** [comment]
Hi,

On  Fr 07 Sep 2018 13:14:28 CEST, Tobi wrote:

> @sunweaver
> I've seen this Debian bug, but I can't quite figure out its status.  
> Seems like someone closed it prematurely and then it was opened again?

I guess, it is work in progress in the Go Lang Debian Packaging Team.  
In Debian, we can't simply bundle shared libs / modules with an  
upstream project, but have to upload all 3rd party components used as  
separate Debian packages. This can be time consuming and the actuall  
work on browsh might seem to stagnate.

Best is, to contact people on IRC (irc.debian.org) #debian-golang or  
email to the person that reopened the bug (see  
https://bugs.debian.org/904132).

Here you find an overview of all not-yet-in-Debian packages that is  
probably being worked on:
https://wnpp.debian.net/?type%5B%5D=ITP&col%5B%5D=dust&col%5B%5D=type&col%5B%5D=description&col%5B%5D=installs&col%5B%5D=owner&col%5B%5D=reporter&sort=dust;asc

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by tobimensch** [comment]
@sunweaver 
I removed some private information from your post, because I suppose you didn't post it intentionally.

**Comment by tobimensch** [comment]
@sunweaver 
And thanks for your informative reply.
