### ISSUE TITLE
Connection to www.seedanddew.com in http server mode every two seconds

### ISSUE THREAD

**Issue by pnhofmann** [browsh-org/browsh#207]
Run browsh with:
``docker run --rm -it -p 4333:4333 browsh/browsh /app/browsh --http-server-mode``

Browsh will open "https://www.brow.sh" and apparently leave this page open as long as browsh runs. Unfortunately your homepage contains a script from "SeedAndDew" - which opens a connection to www.seedanddew.com **every two seconds** (not a bit overdone?) the whole time browsh is running (even if not in use).

~~I'm just using ``--startup-url string`` for other startup page with no scripts.~~ But was quite irritating when I noticed that strange traffic. And I suppose this is somehow "cheating" SeedAndDew.

BTW: A link to SeedAndDew on your homepage would be nice.

**Comment by tobimensch** [comment]
I tentatively agree that every two seconds is too much.

**Comment by pnhofmann** [comment]
I don't really care about the frequency but rather:

Why does browsh http server constantly open http-connections? Even if not actively used and just running somewhere in background?

**Comment by tobimensch** [comment]
@pnhofmann 
I agree this is not desired.

**Comment by pnhofmann** [comment]
Noticed this is actually a bug for https://github.com/browsh-org/www.brow.sh

Guess something like
```
diff --git a/_includes/head.html b/_includes/head.html
index 50ac328..39b3c96 100644
--- a/_includes/head.html
+++ b/_includes/head.html
@@ -13,6 +13,7 @@
   document.documentElement.className = document.documentElement.className.replace(/\bno-js\b/g, '') + ' js ';
 </script>

+{% if page.url != "/html-service-welcome/" %}
 <script>
   var SeedAndDewConfig = {};
   (function() {
@@ -30,6 +31,7 @@
     document.getElementsByTagName('body')[0]).appendChild(snd);
   })();
 </script>
+{% endif %}

 <!-- For all browsers -->
 <link rel="stylesheet" href="{{ '/assets/css/carbonads.css' | absolute_url }}">
```
should do?

**Comment by tombh** [comment]
Neither the Carbon Ads or Seed and Dew script are bringing much money to Browsh. Besides I can actually self-fund the server costs now. So I'd actually be perfectly happy removing all the JS for these services.
