### ISSUE TITLE
Switching search engines / default tabs

### ISSUE THREAD

**Issue by BO41** [browsh-org/browsh#208]
When opening browsh, it opens 2 tabs (google and brow.sh).
I don't think this is needed.

If I want to open an URL I can just edit my current tab (brow.sh as default). And if I want to search for something, I can just focus the url-bar and type ahead.

Also, I don't think google is a good search engine.
1. it is harvesting user data
2. look at the second screenshot, google likes to show stupid popups (and I is impossible to read what it says anyway

maybe this is just my opinion :)

![2018-09-15-154500_529x213_scrot](https://user-images.githubusercontent.com/29450609/45586907-51e58380-b8fe-11e8-9b7f-4e25c4b9c91c.png)

![2018-09-15-154759_1920x997_scrot](https://user-images.githubusercontent.com/29450609/45586931-bc96bf00-b8fe-11e8-97c9-f7027ce428dd.png)

using version 1.4.12 on Archlabs (4.18.7) installed from AUR

**Comment by BO41** [comment]
I am not even able to get rid of the popup. The blue button (what ever it says) is not clickable :disappointed:

**Comment by tobimensch** [comment]
Maybe we can split this issue into multiple issues.

You can edit the default search engine in the configuration file.

I think switching search engines should be easier long term.

We probably need
1) a configuration user interface in browsh
2) a kind of popup to switch the default search engine quickly
3) some conventions like ddg foo bar to search for foo bar on DuckDuckGo while not switching default search engines, so when you search for foo bar it will do so on Google next time, if that's your selected default engine.

I don't really know why the second tab for Google is open. @tombh Can you elaborate?

**Comment by j-rewerts** [comment]
I think having a default search engine that's familiar to most people does have value. I think having it be customizable would be great though.

Love the idea of having some sort of in-browser config for these kinds of things.

**Comment by tombh** [comment]
That's odd that Google is opening up like that. I imagine that'll be something to do with Firefox, as Browsh's job is just to sync Firefox's state.
