### ISSUE TITLE
position: sticky; not supported?

### ISSUE THREAD

**Issue by BO41** [browsh-org/browsh#211]
since the page generation is happening in a headless, modern firefox, why is `position: sticky;`, for example, not respected?

The [sticky](https://www.w3schools.com/cssref/tryit.asp?filename=trycss_position_sticky) property is [supported](https://caniuse.com/#search=sticky) since ff32.

using version 1.4.12 on Archlabs (4.18.7) installed from AUR. Firefox 62

**Comment by tombh** [comment]
Haha :D Look what I found: https://github.com/browsh-org/browsh/commit/e2d39ba56c12e273e5b0af2d5c42cd6d5c62ecd5

Sorry about that. I'm not sure what the best solution is here. What do you think?

**Comment by BO41** [comment]
@tombh well, you are right with all the arguments you mention.
But I don't think the browser should make the rules.
If a webdev decides to use sticky the page should show an element sticky.

I don't know how to improve performance and I can't say much about stuttering.

Maybe make it an option, so if people are annoyed by it, or can't see anything from a webpage, they can turn it off (like it is now).

I like the project and the way it works, but I think it hurts if you don't get the experience you expect, especially since it uses a fully blown firefox and not some own implementation or webkit/webview thing.

**Comment by tobimensch** [comment]
@BO41 
I  agree with you that it should be optional.
