### ISSUE TITLE
Create Windows contrib guide

### ISSUE THREAD

**Issue by j-rewerts** [browsh-org/browsh#212]
Hoping someone can create a getting started guide for contributors on Windows. Would also be nice if they could include the recommended terminal emulator they're using.

**Comment by CodyGramlich** [comment]
Working on one right now.

**Comment by tobimensch** [comment]
@CodyGramlich 
Awesome

**Comment by tobimensch** [comment]
@CodyGramlich 
Thanks for the guide. It looks great.

Do we need another guide for Mac users?
