### ISSUE TITLE
Error reading Windows registry: The system cannot find the file specified.

### ISSUE THREAD

**Issue by tomrow** [browsh-org/browsh#217]
When I try to run BROWSH on Windows 10 AMD64 via CMD.EXE I encounter the error 
`Error reading Windows registry: The system cannot find the file specified.`
Am I doing something wrong or is this a bug?

Never mind, my Firefox was out of date. Please close this issue

**Comment by junkbondtrader** [comment]
I'm seeing this with an up-to-date Firefox. (This is also my first time running Browsh so maybe I'm missing something.)

Nothing jumps out at me in ProcMon (SIDs redacted 😄)
![image](https://user-images.githubusercontent.com/30562087/47620704-9ea6a780-dac3-11e8-82df-2abc27ef1e2c.png)

**Comment by CDBridger** [comment]
+1

**Comment by jspraul** [comment]
I documented how I got brow.sh running on Windows here:

https://github.com/browsh-org/browsh/issues/32#issuecomment-521235581

**Comment by tombh** [comment]
Can anyone try the latest master with #350 to see if this is fixed?
