### ISSUE TITLE
Please use fully qualified imports

### ISSUE THREAD

**Issue by paride** [browsh-org/browsh#238]
browsh has imports like
```
import "browsh/interfacer/src/browsh"
```
in at least three files:

https://github.com/browsh-org/browsh/blob/master/interfacer/src/main.go#L3
https://github.com/browsh-org/browsh/blob/master/interfacer/test/http-server/setup.go#L11
https://github.com/browsh-org/browsh/blob/master/interfacer/test/tty/setup.go#L14

This breaks some build environments, for example the Debian Go packaging toolchain. Changing the imports to fully qualified imports (`github.com/browsh/interfacer/src/browsh`) would ease the Debian packaging work.

**Comment by tobimensch** [comment]
Thanks for reporting this. It's good to know that browsh is in the process of being packaged for major distributions like Debian. I think this will get fixed quickly.
