### ISSUE TITLE
Can I keep Browsh running and use the terminal at the same time?

### ISSUE THREAD

**Issue by BernardoLima** [browsh-org/browsh#242]
Would that be possible?
How can it be done?
Let the browser run in background.

**Comment by claman** [comment]
run it through screen or tmux

**Comment by tobimensch** [comment]
@BernardoLima
Like @claman wrote, you can use a terminal multiplexer to do that.
I'd like to support ctrl+z for sending browsh to sleep (into the background), but in order to make that work @gdamore 's tcell would need to add support first.

Closing this as you can use tmux or screen.
