### ISSUE TITLE
Cannot switch user agent under Mac

### ISSUE THREAD

**Issue by festum** [browsh-org/browsh#244]
Env: Mac OSX 10.14/Firefox 66
Cannot use option+u toggle mobile mode agent

**Comment by anzellai** [comment]
@festum - I'm on Mac OSX 10.14/Firefox 65, `Option + u` does toggle browser agent on my TTY.
I'm using Alacritty with Tmux though.

I don't think this is **Browsh** related issue, it's more likely Mac OSX itself -- terminal sending the incorrect escaped key sequence.

Have you tried configuring your `Option` key as `Alt`/`Meta` under your terminal preferences? That may potentially solve it.

**Comment by tobimensch** [comment]
@anzellai 
I think you may be right. @festum feel free to reopen this issue, if @anzellai's suggestions don't help you.
