### ISSUE TITLE
Use brow.sh in text mode

### ISSUE THREAD

**Issue by Xatenev** [browsh-org/browsh#245]
Hi,

this is not really an issue but I didn't find a related entry in the docs. Basically I want to use the Brow.sh plain text client (https://text.brow.sh/) but in my terminal with the tab line on top just like the regular client. Like a lynx/elinks alternative. Is that currently implemented? 

Thanks!

**Comment by tobimensch** [comment]
@Xatenev 
Hello,

the monochrome mode of the terminal client should behave like you want.

Hope this helps.
