### ISSUE TITLE
How to change config inside browsh docker image?

### ISSUE THREAD

**Issue by niutech** [browsh-org/browsh#252]
I am running browsh in http server mode in docker using this command:
`sudo docker run -itp 4333:4333 --name browsh --rm browsh/browsh /app/browsh --http-server-mode`
However, how can I change the configuration (`startup-url`, `render_delay`, `columns`, etc.) upon starting the server?

**Comment by niutech** [comment]
I managed to do this by running this command:
`sudo docker run -itp 4333:4333 --name browsh --rm browsh/browsh bash -c "sed -i 's/columns = 100/columns = 160/;s/rows = 30/rows = 50/' ~/.config/browsh/config.toml && /app/browsh --http-server-mode"`

**Comment by tobimensch** [comment]
@niutech 
I think that's a good solution.

**Comment by tombh** [comment]
Yeah, nice solution, it can also be done by using file Docker's `mount` argument, eg `--mount type=bind,source=$(pwd)/config.toml,target=/app/config.toml`
