### ISSUE TITLE
Question: How to write loaded website into file or variable(bash)?

### ISSUE THREAD

**Issue by userneu3** [browsh-org/browsh#255]
How to write a loaded website into file or variable(bash)?
Something like this is probably possible, but how:
`browsh https://website.org > dump.txt`
or
`var1=$(browsh https://website.org)`

(I'm only interested in the characters/strings, not in the graphics)
Thank you!

**Comment by tombh** [comment]
I think you're better off using the Browsh online services, in particular https://text.brow.sh

For example:
`curl --insecure https://text.brow.sh/https://github.com/browsh-org/browsh/issues/255 | grep userneu3`

PS: I don't know why my machine's curl is reporting the SSL cert as unrecognised, would be interesting to see if you get the same issue.

**Comment by userneu3** [comment]
Thank you for your answer, text.brow.sh is a nice service.
For me there was no reporting of the SSL cert as unrecognised.
I'd like to append a small question:
Do you know a way to "select all"( CTRL+a) with reregular `browsh https://website.org`?

**Comment by niutech** [comment]
You can run `screen browsh http://example.org` and then type `Ctrl-A H` to log the screen to file `screenlog.n`, then retype `Ctrl-A H` to turn off the log.

**Comment by userneu3** [comment]
Thank you. I'll try this.

Thanks for all answers- I'll close this issue.

**Comment by cipitaua** [comment]
https://text.brow.sh/ service is currently not available. A native offline '-dump' parameter would be very useful.

**Comment by tombh** [comment]
You can run the HTTP server yourself, see these docs: https://www.brow.sh/docs/in-browser-usage/

**Comment by cipitaua** [comment]
totally missed that. yes, much better than nothing but not ideal to use in a script for scraping a webpage

**Comment by cipitaua** [comment]
and indeed it seems not working if I put the process in background:
```
#!/bin/bash
browsh --http-server-mode --time-limit 10 &
sleep 0.5
file=`curl --no-progress-meter --header "X-Browsh-Raw-Mode: PLAIN" localhost:4333/https://github.com/yuzu-emu/yuzu-mainline/releases/latest | grep AppImage | head -1 | awk '{print $1}'`
echo $file
```
when runned in a shell it gives:
```
curl: (52) Empty reply from server
```
while it works fine if I run browsh server in another shell in foreground.
