### ISSUE TITLE
vim-mode-experimental docker image gets stuck waiting for Firefox

### ISSUE THREAD

**Issue by TravisDart** [browsh-org/browsh#265]
I built the Docker image of the vim-mode-experimental branch, but it didn't work. I installed with:

    git clone -b vim-mode-experimental --single-branch https://github.com/browsh-org/browsh.git
    cd browsh
    docker build -t browshvim .
    docker run --rm -it browshvim

It hangs on the "Waiting for Firefox to connect..." screen. - Actually, it seems to display that screen for the normal duration, then it redraws that screen and stays stuck there.

Does anyone know how to get this to work?

**Comment by yasenn** [comment]
Can't reproduce this on Ubuntu 18 x64
App starts in 10 sec. Waiting for firefox takes about 6s.
[Vim commands](https://github.com/browsh-org/browsh/blob/b2ade392237b844f661cd0aa19883961b8a8da16/interfacer/src/browsh/config.go#L77) works

**Comment by TravisDart** [comment]
Was trying this on GalliumOS on an Acer Chromebook 15. Replaced GalliumOS with Arch Linux on the same hardware and it works. Also tried this on OS X and it works there, as well.

**Comment by InconsolableCellist** [comment]
Happens to me on Ubuntu 18.10. Should re-open
