### ISSUE TITLE
Use chafa to render images?

### ISSUE THREAD

**Issue by jxyzn** [browsh-org/browsh#270]
Possible to use chafa (https://github.com/hpjannson/chafa) as the graphic rendering engine? It does a really good job at converting images to the terminal.

**Comment by tombh** [comment]
This has already been discussed a few times, eg; #104 

Basically there certainly are gains to be had, but I don't see them as significant enough to warrant the integration and extra dependencies.

**Comment by phil294** [comment]
for others stumbling upon this issue, the link was wrong, it's https://github.com/hpjansson/chafa
