### ISSUE TITLE
Feature request: is it possible to add it to software "apt install" repro?

### ISSUE THREAD

**Issue by 9527KGG** [browsh-org/browsh#276]
This software is very useful. Is it possible to add it to software "apt install" repro?, such as https://launchpad.net/?

Snap repro should be fine too. However, Windows WSL does not support snap yet. So I think apt install repro is better than snap repro.

Thanks.

**Comment by 9527KGG** [comment]
I've fast network. 

I found this software is very good for privacy. My general practice is: I use tmux to split the screen. 3/4 of the screens shows the code that I am working on. Then I run browsh in the 1/4 screen with alt-m on. Even in the open office, no one notices what web that I am browsing. Very cool~

(I suggest you add the big pro to your frontweb! )

**Comment by tombh** [comment]
Regarding your first point, it's not something that Browsh really has any control over. If Browsh becomes stable and popular enough it will certainly eventually be added. Of course we could also setup a private PPA for it too, but I've never done that so I'll have to leave to someone else for now.

And, yes, haha, that's true Browsh does just look like you're programming or being busy, we should definitely add that to the list of pros on the website!
