### ISSUE TITLE
Windows client fails on Windows 10 with error

### ISSUE THREAD

**Issue by StewAlexander-com** [browsh-org/browsh#288]
@tombh 

Windows client fails on WIndows 10 with registry error

**Comment by rbricheno** [comment]
The error is:

`Error reading Windows registry: The system cannot find the file specified.`

**Comment by tombh** [comment]
Can you try the latest master with #350 to see if this is fixed?

**Comment by StewAlexander-com** [comment]
Sure, sorry for delay

Will report back

**Comment by Kira-Lappo** [comment]
I have the issue in 1.6.4 amd64 on windows 20h2 19042.1052
