### ISSUE TITLE
How does browsh convert image to pixelated versions to render on terminal?

### ISSUE THREAD

**Issue by parrotcar00** [browsh-org/browsh#296]
Sorry if this is too basic of a question but I was trying out browsh few hours back and was looking at a high def image and browsh was showing me a beautiful pixelated version of that image.

I wanted to apply a similar effect to any image outside of browsh and wanted to know how does browsh do this? So basically, how to convert an image to its equivalent that can be displayed on a terminal?

**Comment by tombh** [comment]
There are a lot of projects out there that do this, just have a google for "terminal image viewer github". This looks like a good one, it's maintained and written in Rust: https://github.com/atanunq/viu
