### ISSUE TITLE
HTML and TEXT services are down

### ISSUE THREAD

**Issue by brettalton** [browsh-org/browsh#303]
These services are fully down, I'm not even sure of the response code for them as they appear to be fully deleted from the DNS records. Not sure if it's meant to be down or we need a mirror, but have you considered making a repo for them so people can mirror the service?

https://html.brow.sh and https://text.brow.sh/

**Comment by brettalton** [comment]
https://brow.sh is now down too?

**Comment by tombh** [comment]
Yeah the services have been down for a while :/ Something broke and I just haven't had the time to look into it. I did yesterday try to reinstall everything! But then there was a different problem. I do want to get them back up ASAP, but just life stuff you know, got to prioritise the day job.

**Comment by brettalton** [comment]
No problem! Do what you need to do to stay nourished. I know this has to do with services versus code, so it's not exactly open source in this case, but let us know if there's anything we can help you with to get this back online.

**Comment by tombh** [comment]
They're back up!

Thanks for the support @brettalton :)
