### ISSUE TITLE
Raspberry Pi support?

### ISSUE THREAD

**Issue by Gamegenorator** [browsh-org/browsh#311]
I've got a Raspberry Pi 3 running Resbian, I don't see any binaries specifically for the Pi and the Arm based binaries don't appear to be working.

I've heard of Browsh being used on the Pi, but how do you get it installed?

Do I need to build from the pi? If so do I need to do anything in particular or do I just build it?

**Comment by mahowi** [comment]
I have installed the armv7 deb file and it works on my Raspberry Pi 3.

**Comment by Gamegenorator** [comment]
Odd, It must be an issue on my end, I can't install the armv7.deb from the GUI, but I can from the terminal. I'll take a closer look into the issue on my end, sorry for the confusion.
