### ISSUE TITLE
Request: add to homebrew

### ISSUE THREAD

**Issue by MagnusBrzenk** [browsh-org/browsh#329]
Maybe there used to be a working version on homebrew, but it doesn't appear anymore.

**Comment by tombh** [comment]
This doesn't work? `brew tap browsh-org/homebrew-browsh`

**Comment by spiritphyz** [comment]
I just tried the Mac instructions listed in the [docs](https://www.brow.sh/docs/installation/), and browsh installs and is running fine:
```bash
brew tap browsh-org/homebrew-browsh
brew install browsh
browsh
```

**Comment by ylluminate** [comment]
This should be added to the main repo page and perhaps homepage in a section that explains how to install it. This seems to be the (successful) pattern by most projects today that want to encourage adoption and lower the entry bar.
