### ISSUE TITLE
Is Browsh being maintained?

### ISSUE THREAD

**Issue by StewAlexander-com** [browsh-org/browsh#334]
Is Browsh being maintained?

**Comment by tombh** [comment]
No. I can only just keep on top of issues here and emergency fixes.

**Comment by StewAlexander-com** [comment]
Ok, thanks Tom

**Comment by tombh** [comment]
I do still very much have plans for it though. I have an idea for a new architecture, that'll fix many of the long standing bugs here. Ultimately I'd still love to find a way to make Browsh my day job.

**Comment by StewAlexander-com** [comment]
I too wish it for you, and for me

You could ask for donations in this repo to help support development … over in settings in the repo

Sell some brownsh merchandise to bring in a little cash

Easy to make, check out

https://www.cafepress.com/

Just a few ideas, it's a great product that if people knew about it would be happy to support, I think

**Comment by tombh** [comment]
Thanks :) I've already got a donation page: https://www.brow.sh/donate I make about $50 a month, not bad, but not enough to live off :/

**Comment by StewAlexander-com** [comment]
Better to put it on GitHub   
  
  
  
  

  
Best Regards,
  

  Stew Alexander   
  StewAlexander.com   
  
  
  
  
  

  
  
>

**Comment by StewAlexander-com** [comment]
@tombh well thank you for the reply, if you ever get around to putting a link somewhere on the README.md for donations I and others might want to help support further development

**Comment by tombh** [comment]
Done https://github.com/browsh-org/browsh#donating
