### ISSUE TITLE
Attempting to ssh to brow.sh doesn't work, maybe the server is swamped?

### ISSUE THREAD

**Issue by StewAlexander-com** [browsh-org/browsh#335]
Hi tried to putty ssh to brow.sh and it just hung...

Is the server just swamped?

**Comment by tombh** [comment]
I just had to take them offline, I couldn't figure out how to fix it in time. I have a day job and really need to focus on that :/

**Comment by StewAlexander-com** [comment]
Understand, thanks for the heads up Tom
