### ISSUE TITLE
[QUESTION] Why some sites is uggly ?

### ISSUE THREAD

**Issue by mateushnsoares** [browsh-org/browsh#345]
I have opened youtube and have it:
![image](https://user-images.githubusercontent.com/59037640/95457348-1e437f00-0947-11eb-94ea-aab3c60e890e.png)
It's normal ???

**Comment by 2fst4u** [comment]
What exactly are you expecting this application to do? Have you read what it does and the use-case it actually serves?

**Comment by tombh** [comment]
@mateushnsoares This is exactly how Browsh is supposed to be rendered. It is after all a _CLI_ application that runs in a terminal using nothing but standard UTF8 characters.
