### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by mjuarezm** [browsh-org/browsh#367]
I try to log in to my google account but it shows a message saying that "This browser or app may not be secure."

![2021-02-19-155054_3840x3960_scrot](https://user-images.githubusercontent.com/2465450/108573851-88dbd280-72ca-11eb-9a3b-fffe1dff5a1e.png)

I've tried changing my user-agent to a chrome user-agent but it doesn't work. I've tested javascript and it does work.

I'm using browsh ARMv7 (raspbian for a rpi). I connect to it over mosh. My client is running arch and the terminal is xterm + tmux.

Navigation with browsh works fine so I don't think the debug logs are needed.

**Comment by tombh** [comment]
Oh wow! That's really interesting, I wonder how Google knows?? You tested that the user agent is set correctly with JS? Or I didn't understand that sentence of yours?

**Comment by mjuarezm** [comment]
No, I just tested that the scripts on the page were running correctly and, in addition, that the user-agent is correctly set.

**Comment by mjuarezm** [comment]
I think I figured it out, BTW. The problem is that I have two-factor authentication in my google account and that disables this option:

https://myaccount.google.com/lesssecureapps

Apparently, Google considers browsh a "less secure app". To workaround this, you can generate an app-specific password for browsh.

**Comment by tombh** [comment]
That's really interesting, thanks for reporting that. And good to know there's a solution 🙂

**Comment by speron26** [comment]
Hi,

I have the same problem .... 

Google says : 
"To help secure your account, as of May 30, 2022, Google will no longer support the use of third-party apps or devices that only ask for your username and password to sign in to your Google Account. Important: This deadline does not apply to Google Workspace or Google Cloud Identity customers. The effective date for these customers will be announced on the Workspace blog at a later date. To learn more, read on."

So there is no more way to generate a specific password for brow for a google account ;-(

:-)
