### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by tombh** [browsh-org/browsh#37]
So that user's preferences can be saved and Browsh can be started in particular state, eg; starting in Monochrome mode.

**Comment by thornjad** [comment]
Could there be included in a config file some basic browser preferences, such as search engine and home pages? And/or a way to use an existing Firefox profile (if that's possible for headless mode)?

**Comment by tombh** [comment]
For sure, I already set some custom FF preferences in the code, so just augmenting them with user-set lines in the config will be easy.

**Comment by drodil** [comment]
Would love to see also configuration for keyboard shortcuts (as in: VIM mode would be awesome)

**Comment by thornjad** [comment]
@drodil Vim mode is already being talked about in #31, but config of it would certainly be good, even if just enabling or disabling.

**Comment by tombh** [comment]
This was solved in #112
