### ISSUE TITLE
Docker arm(64) image

### ISSUE THREAD

**Issue by 2fst4u** [browsh-org/browsh#374]
Any possibility of compiling an arm or arm64 image for the docker image? Ideally as a multi-arch label for ease of use.

It would be awesome because then people could run it on a raspberry pi.

**Comment by tombh** [comment]
So we'd use one of the releases from here? https://github.com/browsh-org/browsh/releases

**Comment by 2fst4u** [comment]
Sure, I'm not sure what the process is to create a docker image but if it just gets rolled into the latest tag with multiple architectures then it can be pulled on any compatible architecture.

**Comment by tombh** [comment]
Sure, ok 👍

**Comment by 2fst4u** [comment]
Sorry to be a massive pain, but is that a yes? Just wondering if this is in the pipeline to happen one day.

Not rushing, just curious.

**Comment by tombh** [comment]
I've just not been developing Browsh enough recently for this to be trivial. The main thing is having to revisit the build system, which unlike Browsh, doesn't get used that much. I think the reality is, that until I get enough savings to be back on Browsh full time, this won't happen 😕

**Comment by samveen** [comment]
Looks like I'll need to figure out github action pipelines for multi-arch to go with #460 :face_exhaling:
