### ISSUE TITLE
Browsh looks funny on Mac

### ISSUE THREAD

**Issue by munro** [browsh-org/browsh#384]
Hey!  I tried to find how to fix this, but I couldn't find anyone else with this issue, and I'm really not sure why this is happening, but here's what https://www.wikipedia.org looks like for me:

![Screen Shot 2021-08-05 at 7 43 15 PM](https://user-images.githubusercontent.com/500774/128435349-f0a15b9f-7d48-4d49-ab6c-0aebc18c032f.png)

Type | Value
-|-
OS | macOS Big Sur v11.4
Terminal | Terminal.app

My `debug.log`:  https://gist.github.com/munro/106e8c870edf8019c86c4e3c308a30e9

Installed with brew:
```bash
brew tap browsh-org/homebrew-browsh
brew install browsh
```

**Comment by munro** [comment]
And here is `browsh --firefox.with-gui` using `Terminal.app`'s Basic theme:
![Screen Shot 2021-08-05 at 7 54 57 PM](https://user-images.githubusercontent.com/500774/128435851-6449212c-a57e-4a87-9f92-acce65e4d469.png)

**Comment by tombh** [comment]
I think that's down to lack of true colour, there's some more info here https://www.brow.sh/docs/terminals

**Comment by munro** [comment]
Oh wow, yes, thank you!

**Comment by tombh** [comment]
😃

**Comment by munro** [comment]
@tombh wow ty, I don't know what just happened, but now I'm using Alacritty & Amethyst (tiled window manager for Mac) 🤣🤣🤣

**Comment by tombh** [comment]
Hhahaha, Browsh is a gateway drug 🤣🤣🤣

**Comment by munro** [comment]
![Screen Shot 2021-08-05 at 10 03 20 PM](https://user-images.githubusercontent.com/500774/128444738-e4304358-9f88-4c7d-ab42-9e322f1efce9.png)

lmao what am i doing

**Comment by tombh** [comment]
OMG so cool 🤓

**Comment by martin-braun** [comment]
<img width="816" alt="Screen Shot 2023-01-19 at 1 21 26 PM" src="https://user-images.githubusercontent.com/24259245/213442142-321cbcaa-dcfb-4161-b02f-7334b17827f9.png">

Looks not cool for me either. I use iTerm2, `echo $TERM` prints `xterm-256color`, so why is it still looking ugly?

**Comment by tombh** [comment]
Do you have true color setup? https://github.com/termstandard/colors

**Comment by martin-braun** [comment]
@tombh Yes I have, but now it works and I can't really reproduce it.
