### ISSUE TITLE
Double-with character (e.g. Asian character) cannot be displayed correctly

### ISSUE THREAD

**Issue by Freed-Wu** [browsh-org/browsh#393]
![Screenshot from 2021-11-06 14-48-45](https://user-images.githubusercontent.com/32936898/140600786-14d404f2-5b23-49f3-9f4c-9e3f2c80e6e5.png)
![Screenshot from 2021-11-06 14-48-42](https://user-images.githubusercontent.com/32936898/140600792-064faed4-96ac-4836-b1f0-6e4598106503.png)

In this web page, `linux_百度搜索` becomes `linux_百搜`.  `linux_百度
百科` becomes `linux_百百`.

**Comment by tombh** [comment]
This is a duplicate of #75
