### ISSUE TITLE
it is posible see true images

### ISSUE THREAD

**Issue by alavaelian** [browsh-org/browsh#405]
i mean not image in ascii instead actual images in a terminal like w3m ? o and it possible watch a youtube video ?

**Comment by tombh** [comment]
Not yet, but it's being considered in #86.

**Comment by alavaelian** [comment]
well sorry but maybe using a frame buffer for tty , i am able to read pdf and see images and videos in a tty through frame buffer
for the video i just do vlc -I ncurses

**Comment by Xeddius** [comment]
Sending the framebuffer is actually costly bandwidth wise, the main point of browsh is to be able to use the full web on a device without the power/network/resources to normally do so. I know there are a few scripts for youtube-dl to pipe video directly to framebuffer with mplayer, you could use that for youtube. For browsing with images loaded into the framebuffer I suggest you take a look at `links2` cli+graphical browser.
