### ISSUE TITLE
Website not Loading

### ISSUE THREAD

**Issue by Joel05** [browsh-org/browsh#408]
I am trying to connect to my Routers Configuration Website from my Ubuntu-Server. I am currently on Vacation, but i need to forward some Ports, and the only way to connect to my Routers Config is by being inside its network. So i thought that i could connect through my server, which is in the Routers network. But if i try to open the Website, not much is happening. The Name of the Website stays "192.168.200.100" (which is my routers ip, which i am trying to connect to) until i switch tab, then it Changes to "Mobile Router Configuration" which seems right, but the website is still not loading. Any ideas how i can resolve this?

**Comment by tombh** [comment]
I think a better way of doing this is by tunnelling ports with something like https://ngrok.com
