### ISSUE TITLE
is lora enough to use browsh 

### ISSUE THREAD

**Issue by alavaelian** [browsh-org/browsh#410]
is lora enough to use browsh browser if not withch other network could do that

**Comment by tombh** [comment]
What is "lora"?

**Comment by alavaelian** [comment]
https://en.wikipedia.org/wiki/LoRa is a  network protocol  there are plenty of people making proyect with this protocol suitable for iot aplications very long range

**Comment by tombh** [comment]
Browsh needs only a few Kbps of bandwidth, so I imagine, yes, LoRa is enough for Browsh.

**Comment by alavaelian** [comment]
browsh is a amazing proyect keep it up, good work
