### ISSUE TITLE
Failed to connect to Firefox's Marionette within 30 seconds

### ISSUE THREAD

**Issue by jerwah** [browsh-org/browsh#419]
Trying to get this running on some very ancient hardware. (Ubuntu 20.04 )

When executing browsh it does find Firefox, and does spawns it however it times out after 30 seconds with:
Failed to connect to Firefox's Marionette within 30 seconds

Attempt to run again immediately I get:
A headless Firefox is already running

killall firefox, try again, same result. debug log included below. 

Saw some posts related to this error, but they were all regarding proxies, and the website not responding, etc. None of those are applicable per se to this situation. No proxies and I'm just trying to open https://www.google.com for now.  w3m successfully loads the same page in under a second. 

I have 2 theories. 

#1 - Firefox is actually taking slightly longer than 30 seconds to load. I mean it IS really old hardware. Perhaps adding a parameter to be able to set the 30 second limit to any arbitrary value would be helpful?  

#2 - Due to its age, I need to run only what is absolutely necessary, so there's no X environment on the box, at all. The machine in question is truly headless. Doesn't even have a monitor on it. I found some posts in the Firefox forums which imply that Firefox might not even try to load a page unless you have a functioning window manager. 

Personally, I'm leaning towards #2 as being the actual root cause of my issues. If that's the case, then having a functioning WM should be added to the pre-requisites. Either way, adding a parameter to do something other than 30 hardcoded seconds is probably a good thing just in general. 

Thanks!

Attached: browsh-testing.txt
1 - Attempt to connect with debug turned on - shows timeout
2 - ps -Af | grep firefox - shows firefox did attempt to start
3 - dump debug.log
4 - Attempt to launch browsh again - A headless Firefox is already running

[browsh-testing.txt](https://github.com/browsh-org/browsh/files/8887681/browsh-testing.txt)

**Comment by tombh** [comment]
Thanks for the report. I'm curious, as this is a common misconception about Browsh that it should be run in the same place you use it, what can I do to make it clearer that this is not how Browsh is supposed to be used. It says in the [homepage](https://www.brow.sh/), "Its main purpose is to be run on a remote server and accessed via SSH/Mosh". Why is it that you didn't come across that description?

**Comment by jerwah** [comment]
My specific use case is that I need to run a javascript enabled browser on the remote host. I am working to setup rclone and to be able to mount google drive to it you must sign-in to authorize your API key. This step requires navigation to a 127.0.0.1 hosted page that redirects you to google for login. rclone advanced setup does have an OOB method of authorizing the key, to avoid this localhost need, but it appears google has closed that particular loophole, so in the interim, the only viable method is to run a browser locally on the remote host and it must support javascript. That combination of google searches led me to browsh.  

This morning though, I ran a test. I fired up an XServer on my laptop, tunneled to the box and launched Firefox. Total start time was 57 seconds. So it appears theory 1 was actually the issue, so adding a firefox start timeout parameter would have allowed it to work.

The good news for me is that since I got Firefox working in the tunnel, my specific short-term need is now moot as I was able to authorize my key.  I acknowledge that this is a weird edge case but I can also think of other times where I've wanted to quickly test localhost web resources with a browser, without necessarily opening up firewall holes, etc.  the typical suspects like w3m/lynx et al will usually suffice, but having one with javascript capabilities is a game changer. 

Either way, very cool project, definitely keeping this in my toolbox. 

Thank you.

**Comment by tombh** [comment]
Ok, that's understandable. Thanks for the debug logs, I can't see anything obvious. Also, I'm not focussing on Browsh much these days, so don't have much time to look into it, I'm afraid to say

**Comment by a8underscore** [comment]
Hey jerwah, the rclone advanced method has worked for me in the last couple of weeks, perhaps it is user error on your end that is prevent it from working?

another great way to solve your rclone issue is to configure everything locally and just copy the rclone config, i do this often

**Comment by jerwah** [comment]
> Hey jerwah, the rclone advanced method has worked for me in the last couple of weeks, perhaps it is user error on your end that is prevent it from working?

Can't ever rule out keyboard actuator issues, but I got an exact hit on the errors I was getting back from Google that tied to a change in the oob process, so I don't think it was me, this time... 


> 
> another great way to solve your rclone issue is to configure everything locally and just copy the rclone config onto the remote, i do this often

Doh, wish I had thought of that earlier. Great suggestion. Either way I got it all working. 

Thank you
