### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tenleftfingers** [browsh-org/browsh#433]
Binary was downloadede from: https://github.com/browsh-org/browsh/releases/download/v1.6.4/browsh_1.6.4_linux_amd64.deb

  * contents of your `./debug.log` generated with `browsh --debug`
`Looking in /home/iarla/.config/browsh/config.toml for config.
Attempting to connect to Firefox Marionette
Starting Firefox in headless mode
Using Firefox at: /usr/bin/firefox
Using default profile at: /home/iarla/.config/browsh/firefox_profile
debug.log (END)
`
  * Include your OS and terminal name
Ubuntu 22.04 
gnome-terminal
Firefox 102.0.1 (64-giotán)

The logs contained not much info, but more output was printed to the screen. It wasn't selectable so I've attached a screenshot:
![screenshot](https://user-images.githubusercontent.com/1757768/179401887-b2d88fc8-3411-44fe-81e6-c736c5916e2e.jpg)

**Comment by null1024** [comment]
Having the same issue here, Ubuntu 22.04, Firefox 102.0.1, connected to the machine over SSH with PuTTY. Identical debug output, only difference is my username.
Browsh 1.8.0, 64-bit.

**Comment by tenleftfingers** [comment]
Thanks. I forgot about the snap. Problem solved :)

**Comment by ioogithub** [comment]
Same issue as this one: https://github.com/browsh-org/browsh/issues/446

**Comment by jerubball** [comment]
Also same as #509,

Here is solution I found:

Modify your config file located at `~/.config/browsh/config.toml` and add following line to **[firefox]** section

```
path = "/snap/firefox/current/usr/lib/firefox/firefox"
```
