### ISSUE TITLE
Any new releases ? 

### ISSUE THREAD

**Issue by dirkpetersen** [browsh-org/browsh#434]
I noticed there have not been any new releases since 2019. Would it make sense to release a new version so people can easily test the latest code ?

**Comment by dirkpetersen** [comment]
Awesome, this is a very cool project. I can be quite useful for high performance computing users who only have direct shell access to their organization via an SSH gateway. To get to the documentation of their system they have to use a VPN connection which introduces additional latencies for very remote users. I plan to test browsh with the popular mkdocs material skin, for example seen at https://docs.nersc.gov/

**Comment by tombh** [comment]
Wow, that'd be cool to know that Browsh is an essential part of super computers haha 🤓

**Comment by tombh** [comment]
And here it is: https://github.com/browsh-org/browsh/releases/tag/v1.8.0

**Comment by dirkpetersen** [comment]
Awesome, thank you !!
