### ISSUE TITLE
can i use browsh into a low ram systems?

### ISSUE THREAD

**Issue by alavaelian** [browsh-org/browsh#459]
i mean it can be another reason to use brows if you dont need to have an instance of firefox running in the background.

**Comment by tombh** [comment]
This is actually what Browsh is designed for. The idea is to SSH from the low-powered machine into a high-powered machine that's running Browsh.

**Comment by alavaelian** [comment]
man this proyect is my favorite one in the open source community if it spreads it could work great stuff like using a  Radxa Zero as  daily desktop or using an antique pc  i love it thanks for you job.

**Comment by tombh** [comment]
Wow, thank you 😊
