### ISSUE TITLE
[Bug report] Windows: Waiting for Firefox to connect ...

### ISSUE THREAD

**Issue by Dragon1573** [browsh-org/browsh#501]
## Related issues

- https://github.com/microsoft/winget-pkgs/issues/104234
- https://github.com/browsh-org/browsh/issues/491
- https://github.com/browsh-org/browsh/issues/483
- https://github.com/browsh-org/browsh/issues/474
- https://github.com/browsh-org/browsh/issues/441

## Description

> During manually validation in Windows Sandbox, `browsh.exe` cannot launch `Mozilla.Firefox` (installed via `winget.exe`). I think this behaviour is not expected.
> 
> ![image](https://private-user-images.githubusercontent.com/49941141/291612318-e9ca9c06-48fc-423b-a079-adf5a612fb36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODMyNDUsIm5iZiI6MTcwMzA4Mjk0NSwicGF0aCI6Ii80OTk0MTE0MS8yOTE2MTIzMTgtZTljYTljMDYtNDhmYy00MjNiLWEwNzktYWRmNWE2MTJmYjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDE0MzU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExOWViYjZhOGY2MTNkYzU3NDlkNzU2OTkxZjM3ZGE1MzYzMzUyOWE1NDY1ZTQ1Y2M4YTUzNmI2ZDYxOTgwMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8aq9FMx3S309prk2vGMtXFXNEWHkuc72IWj2D1I2T68)

## Logs

<details>

```text
Looking in C:\Users\WDAGUtilityAccount\AppData\Roaming\browsh\config.toml for config.
Attempting to connect to Firefox Marionette
Starting Firefox in headless mode
Windows registry Firefox version: 120.0.1
Using Firefox at: C:\Program Files\Mozilla Firefox\firefox.exe
Windows registry Firefox version: 120.0.1
Using default profile at: C:\Users\WDAGUtilityAccount\AppData\Roaming\browsh\firefox_profile
Sending `WebDriver:NewSession` to Firefox Marionette
Sending `Addon:Install` to Firefox Marionette
Starting Browsh CLI client
Starting websocket server...
FF-MRNT: 50:{"applicationType":"gecko","marionetteProtocol":3}
Webextension not connected. Message not sent: /tty_size,146,42
FF-MRNT: 1106:[1,1,{"error":"unknown error","message":"Expected absolute path: [Exception... \"Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath]\"  nsresult: \"0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)\"  location: \"JS frame :: chrome://remote/content/marionette/addon.sys.mjs :: install :: line 70\"  data: no]","stacktrace":"RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:189:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:768:5\ninstall@chrome://remote/content/marionette/addon.sys.mjs:72:13\nGeckoDriver.prototype.installAddon@chrome://remote/content/marionette/driver.sys.mjs:2953:21\ndespatch@chrome://remote/content/marionette/server.sys.mjs:318:40\nexecute@chrome://remote/content/marionette/server.sys.mjs:289:16\nonPacket/<@chrome://remote/content/marionette/server.sys.mjs:262:20\nonPacket@chrome://remote/content/marionette/server.sys.mjs:263:9\n_onJSONObjectReady/<@chrome://remote/content/marionette/transport.sys.mjs:494:20\n"},null]
Webextension not connected. Message not sent: /tty_size,146,42
FF-CONSOLE: [GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
FF-MRNT: 683:[1,0,null,{"sessionId":"435a1a28-ae7e-43cd-92dc-4dd8d2b023c6","capabilities":{"browserName":"firefox","browserVersion":"120.0.1","platformName":"windows","acceptInsecureCerts":false,"pageLoadStrategy":"normal","setWindowRect":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"strictFileInteractability":false,"unhandledPromptBehavior":"dismiss and notify","moz:accessibilityChecks":false,"moz:buildID":"20231129155202","moz:headless":true,"moz:platformVersion":"10.0","moz:processID":1912,"moz:profile":"C:\\Users\\WDAGUtilityAccount\\AppData\\Roaming\\browsh\\firefox_profile","moz:shutdownTimeout":60000,"moz:webdriverClick":true,"moz:windowless":false,"proxy":{}}}]
Sending `Marionette:Quit` to Firefox Marionette
*errors.errorString normal
/home/runner/work/browsh/browsh/interfacer/src/browsh/tty.go:113 (0x4d283d)
/home/runner/work/browsh/browsh/interfacer/src/browsh/firefox.go:311 (0x4ca8c5)
/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/asm_amd64.s:1571 (0x1e31c1)
```

</details>

## Environments

- Windows 11 Professional 23H2 (22635.2915)
- Windows Feature Experience Pack 1000.22682.1000.0
- Windows Sandbox
  - Windows 11 Enterprise 22H2 (22621.2915)
  - Windows Package Manager v1.6.3482 
    - Mozilla Firefox (x64 en-US) 120.0.1
    - Browsh 1.8.2

**Comment by tombh** [comment]
In microsoft/winget-pkgs#104234, you had some suggestions for changes? Would you like to make a PR so others can test it?

**Comment by Dragon1573** [comment]
Okay, I'll try if it can help. 😄

**Comment by Dragon1573** [comment]
The pull request is successfully merged, but I failed to build the executable on my own.

Will validate the patch manually later. :smile:

**Comment by Dragon1573** [comment]
`Tools/SandboxTest.ps1` is currently unavailable because there's an error in the script file. Moderators of _microsoft/winget-pkgs_ are currently working on it.

Just create [a pull request](https://github.com/microsoft/winget-pkgs/pull/136968) without verify the manifest locally. If it can pass the installation, then #502 is proved to be a valid patch.

**Comment by Dragon1573** [comment]
Microsoft Azure Pipelines of that pull request is successfully passed. This is a valid fix ❤️

- https://github.com/microsoft/winget-pkgs/pull/136968#issuecomment-1914806549

**Comment by tombh** [comment]
Awesome! I'll make a new release then.
