### ISSUE TITLE
[feature] json schema support

### ISSUE THREAD

**Issue by Freed-Wu** [browsh-org/browsh#505]
Can `~/.config/browsh/config.toml` have a [json schema](https://json-schema.org/) and been published in [schemastore](https://www.schemastore.org/json/)?

**Comment by tombh** [comment]
Sure! PRs welcome.

**Comment by Freed-Wu** [comment]
This is a reference: <https://github.com/cmhughes/latexindent.pl/issues/206>

The steps are following:

1. Create a json schema
2. Add its URL to schemastore.
