### ISSUE TITLE
Opening browsh in xfce terminal with white background looks weird

### ISSUE THREAD

**Issue by olleharstedt** [browsh-org/browsh#60]
See screenshot.

https://snag.gy/vhpetL.jpg

**Comment by tombh** [comment]
Does any of the "Terminals" section of the docs help here? https://www.brow.sh/docs/terminals/ (currently Google has flag my *.brow.sh domains as phishing risks, so you may have a problem seeing the docs).

But basically you should only need to enable true colour support for your terminal.

**Comment by olleharstedt** [comment]
Hm, it works as expected in xterm. Changing colorscheme to white-on-black helps, but still have issues. Maybe it's the font, Ubuntu Mono 11?

https://snag.gy/dlXmqh.jpg

**Comment by tombh** [comment]
That's definitely lack of true colour support

**Comment by tombh** [comment]
It says here that XFCE terminal support true colour: https://gist.github.com/XVilka/8346728

> libvte-based xfce4-terminal - since 0.6.90 release, if compiled with GTK+3

**Comment by olleharstedt** [comment]
OK, I'm using an older version of the terminal. Closing the issue.

**Comment by ScoreUnder** [comment]
I get the same problem in urxvt. Running it under tmux seems to be a viable workaround. Either way it's likely a bug in browsh rather than in the terminal.

**Comment by tombh** [comment]
This issue was definitely caused by not having true colour.

If you search this page https://gist.github.com/XVilka/8346728 for "urxvt" you'll see that it doesn't support true colour, but someone has made a patch for it.
