### ISSUE TITLE
Docker image fails to run, possibly OSX related

### ISSUE THREAD

**Issue by tombh** [browsh-org/browsh#62]
When running `docker run -it browsh/browsh`, user gets: `standard_init_linux.go:185: exec user process caused "exec format error"`.

Their Docker details;

```
$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by zutto** [comment]
well, this is interesting..
```
$ docker run -it browsh/browsh /bin/bash -c "cat /app/browsh"
Not Found
```

the browsh file literally has "Not Found" text inside it, nothing else..

**Comment by psafont** [comment]
Same problem here on Linux:

```
$ docker version
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   f150324782
 Built:        Wed May 16 22:27:45 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.2
  Git commit:   f150324782
  Built:        Wed May 16 22:28:17 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

```
$runc --version
runc version 1.0.0-rc5+dev
commit: 69663f0bd4b60df09991c08812a60108003fa340
spec: 1.0.0
```

**Comment by zutto** [comment]
Yeah, the build on dockerhub has failed, rebuilding the docker from scratch works, and the /app/browsh is actually a binary and not text file saying 'not found'.

**Comment by tombh** [comment]
Thanks for the detective work folks! I found the problem. Pulling the latest image should work now: `docker pull browsh/browsh`

All the time before publicising Browsh I was only using tagged builds which get triggered on Docker hub *after* Travis has successfully run the test suites and built all the binaries -- namely binaries which are downloaded by Docker hub. However, the non-tagged (ie `browsh/browsh:latest`) Docker images are triggered at the moment of push to Github, so *before* the binaries have been built.

I don't know what the best solution is. Ideally I want to alias the latest tagged version to `latest`. I'll look into the best solution, so I won't close this just yet.

**Comment by zutto** [comment]
https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c this probably could help.

Also, you should add `--fail` flag to the curl at https://github.com/browsh-org/browsh/blob/master/interfacer/contrib/setup_browsh.sh#L24 to ensure that no silly stuff like this happen, it will cause the docker build to fail if the web server returns something other than 200-OK.

**Comment by tombh** [comment]
The thing about the release is that at that the moment the latest one is the previous version, so I need a way to postpone the Docker Hub build until after the binary has been released. I'll look to see if Docker Hub as a manual webhook trigger.

Ah yes, excellent suggestion about the `--fail` arg. And maybe a `set -e` at the top as well.

**Comment by kim0** [comment]
Confirmed fixed for me

**Comment by tombh** [comment]
Reminder to self: don't close this issue until you've fixed the Travis CI build race condition!

**Comment by tombh** [comment]
Ok, this should be fixed now. https://hub.docker.com/r/browsh/browsh/builds/

Now Docker images *only* get built for tagged commits, which only ever occur after a successful Travis build with the fresh binaries has occurred. So from now on `docker run -it browsh/browsh` will always point to the latest tagged version. Which at the moment is equivalent to `docker run -it browsh/browsh:v1.3.2`
