### ISSUE TITLE
Mouse interaction causes runtime error

### ISSUE THREAD

**Issue by MrSrsen** [browsh-org/browsh#63]
Hello there.
I was trying your application trough public SSH demo server and when i connected i get this error.

```
martin@martin-mbp:~$ ssh brow.sh
Welcome to brow.sh (1.2.0)
Starting your public session, which will only last 5 minutes and be logged.
Startup URL: https://www.brow.sh/ssh-welcome
Please wait...
Logging to: /app/debug.log

      ***********************                                                                 
                                                                                              
Starting Browsh, the modern text-based web browser.                                           
Waiting for Firefox to connect...                                                             
                                                                                              
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6de976]

goroutine 24 [running]:
browsh/interfacer/src/browsh.handleMouseEvent(0xc42022bf20)
	/home/travis/gopath/src/browsh/interfacer/src/browsh/tty.go:151 +0x36
browsh/interfacer/src/browsh.readStdin()
	/home/travis/gopath/src/browsh/interfacer/src/browsh/tty.go:46 +0xd3
created by browsh/interfacer/src/browsh.TTYStart
	/home/travis/gopath/src/browsh/interfacer/src/browsh/browsh.go:185 +0xf2
Connection to brow.sh closed.
martin@martin-mbp:~$ 35;1;13M0;1;13M32;2;13M32;3;14M32;4;14M32;5;14M32;6;14M32;7;14M0;7;14m
```
Application crashed and it's keeping getting errors as i was moving cursor over terminal window.

**Comment by tombh** [comment]
Oh, how interesting. I wonder if OSX terminal sends unusual mouse escape sequences? Did you try more than once? And also try without ever putting the mouse inside the terminal pane.

**Comment by MrSrsen** [comment]
Yes and I also tried terminal on XQuarts.

**Comment by tombh** [comment]
Thanks :)

I've never heard of XQuarts, how recent is it? That screenshot it is definitely caused by lack of true colour support. This page lists all the currently known true colour terminals: https://gist.github.com/XVilka/8346728

**Comment by tombh** [comment]
It looks pretty likely that Terminal.app doesn't actually support true color :( It's not mentioned as a working terminal here: https://gist.github.com/XVilka/8346728 and this comment from 4 years ago, seems to confirm it: https://gist.github.com/XVilka/8346728#gistcomment-1363096

Apparently your best choice is iTerm2.#

**Comment by puppycodes** [comment]
+1 getting this error

**Comment by albill** [comment]
I'm seeing the same problem on current OS X trying to run it through the Docker image with 

docker run -it browsh/browsh

**Comment by tombh** [comment]
So the referenced line `tty.go:151` deals with mouse coords. So I wonder what happens if those with this error can reliably reproduce the error by starting browsh with the mouse outside the terminal window, then just moving the mouse inside to trigger the error.

Either way running browsh with the `-debug` argument and sending me any relevant parts of `./debug.log` might reveal something.

**Comment by puppycodes** [comment]
I'm also using Iterm2, I think the issue might be outside of the native osx terminal

```
Starting Browsh, the modern text-based web browser.
Waiting for Firefox to connect...panic: runtime error: invalid memory address or nil pointer dereference
                                        [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10a73fe]

                                               goroutine 19 [running]:
      os.(*Process).signal(0x0, 0x13d6a60, 0x152c2b0, 0x0, 0x0)
home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec_unix.go:56 +0x2e
             os.(*Process).Signal(0x0, 0x13d6a60, 0x152c2b0, 0xc420227e90, 0x18)
                        /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec.go:129 +0x3f
                                  os.(*Process).kill(0x0, 0xc420076928, 0xc420227e90)
                     	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec_posix.go:54 +0x43
                                       os.(*Process).Kill(0x0, 0x4, 0x4)
        	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec.go:114 +0x2b
                          browsh/interfacer/src/browsh.startHeadlessFirefox()
             	/home/travis/gopath/src/browsh/interfacer/src/browsh/firefox.go:84 +0x365
```

**Comment by tombh** [comment]
Thanks. Could you try running browsh with the `-debug` argument and sending me any relevant parts of `./debug.log`.

**Comment by puppycodes** [comment]
debug.log
```
Attempting to connect to Firefox Marionette
Starting Firefox in headless mode
Using default profile at: /Users/******/Library/Application Support/browsh/firefox_profile
```

**Comment by tombh** [comment]
Right, I've reproduced this exact error with Terminator. Now I can try out some various fixes. Watch this space!

**Comment by fmauNeko** [comment]
I had the same issue on my Archlinux, and I found out it happens only when I start browsh and then focus another window (easy to do as I use i3).
When I keep the mouse over the terminal I opened browsh in until it starts, it works fine.
I'm using Tilix under i3-gaps.

**Comment by MrSrsen** [comment]
Works for me. If you don't mind i close this issue. Thanks for fix. :)

**Comment by Xses-1** [comment]
Doesn't work for me on Konsole
