### ISSUE TITLE
project web-page marked as malware/phishing by google

### ISSUE THREAD

**Issue by zutto** [browsh-org/browsh#64]
so.. google says that brow.sh marked as malware, whats up with that?
https://transparencyreport.google.com/safe-browsing/search?url=brow.sh
even trying to access the dockerhub page blows out a warning.

Has something been compromised?

![unafe](https://user-images.githubusercontent.com/4032653/42443866-572a7bb4-8377-11e8-905c-8472e0b94de6.jpeg)

**Comment by tombh** [comment]
As already explained in #58
 
> This is caused by the fact that the live HTML service can render sites like: https://html.brow.sh/http://mail.google.com Google then detects that as an attempt to phish Gmail user's usernames and passwords. The HTML service only returns plain text, `<pre>` & `<a>` tags, not even any JS. So it's actually impossible for a phishing attack to occur. I've disabled the HTML services ability to parse Gmail now and submitted a review to Google a few hours ago. But Google said it could take up to 72 hours :/

But wow, that's awful that even Docker Hub throws an error. This was supposed to be a special day for me :''''''(

**Comment by DanielRuf** [comment]
> But wow, that's awful that even Docker Hub throws an error. This was supposed to be a special day for me :''''''(

Had to make the same bad experience when I wrote desktop software in the past and one after another AV vendor marked my software as malicious. Was much work to contact them and get the warning removed. But this was not with Google Safebrowsing.

So far the Google Safebrowsing team should be fast and it often takes less hours to remove the warning and whitelist the domain.
