### ISSUE TITLE
Make available for Homebrew

### ISSUE THREAD

**Issue by SimenB** [browsh-org/browsh#65]
Hiya! 👋 

I started putting together a PR for homebrew for this package, but the build is a bit convoluted for me. But goreleaser supports publishing a Tap, do you think you could set that up?

Docs: https://goreleaser.com/homebrew/

**Comment by tombh** [comment]
Absolutely! It was already on my list of things to do.

**Comment by tombh** [comment]
So I've got this repo being automatically updated for every version now: https://github.com/browsh-org/homebrew-browsh

This is my first Tap recipe, so any guidance would be much appreciated. From what I can gather you can now do `brew tap browsh-org/homebrew-browsh`?

**Comment by SimenB** [comment]
Awesome!

The firefox dependency messes it up, I think.

```sh-session
$ brew tap browsh-org/homebrew-browsh
==> Tapping browsh-org/browsh
Cloning into '/usr/local/Homebrew/Library/Taps/browsh-org/homebrew-browsh'...
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
Tapped 1 formula (26 files, 20.2KB).
$ brew install browsh-org/browsh/browsh
==> Installing browsh from browsh-org/browsh
Error: No available formula with the name "firefox" (dependency of browsh-org/browsh/browsh)
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by SimenB** [comment]
Having some message printed (make sure to also have firefox installed!) or something seems reasonable to me 🙂

**Comment by tombh** [comment]
Ok, so I just removed the line referencing the Firefox dependency. Do you think if I use the `caveats` field to print out the note about Firefox, that'll be ok: https://goreleaser.com/homebrew/

**Comment by SimenB** [comment]
Yeah, now it works 🙂 `caveats` seems reasonable to me!

**Comment by tombh** [comment]
Added. That'll take effect in the next version release :)

**Comment by revolter** [comment]
So would you be able to install it using `brew install browsh`?

**Comment by tombh** [comment]
Can someone else answer @revolter's question. I'm not a Mac user so wouldn't know. Thanks.

**Comment by revolter** [comment]
This applies to Linux too 😛: http://linuxbrew.sh _(Partly kidding, as I know brew is not that used on Linux)_

**Comment by SimenB** [comment]
`brew tap browsh-org/homebrew-browsh && brew install browsh-org/browsh/browsh`

**Comment by revolter** [comment]
Is there something holding you back from publishing it to the default tap (if that's what is called)?

**Comment by revolter** [comment]
`brew tap browsh-org/homebrew-browsh && brew install browsh` also works.

**Comment by tombh** [comment]
I don't know about the default tap, but I'm happy to do whatever people here think is best. Let me know...

**Comment by kutsan** [comment]
@tombh Submit a PR like this one: https://github.com/Homebrew/homebrew-core/pull/29803

**Comment by revolter** [comment]
Should it be a cask or not?

**Comment by kutsan** [comment]
@revolter It shouldn't be a cask and it can't be because it's a command-line application.
