### ISSUE TITLE
Wrong font-size on Wikipedia articles

### ISSUE THREAD

**Issue by niutech** [browsh-org/browsh#70]
When browsing [Wikipedia](https://html.brow.sh/https://en.wikipedia.org/wiki/Internet) using Chrome/Firefox on Windows 10 with `devicePixelRatio=1.25`, the article text has too small left padding (see screenshot below). Setting the `font-size: 16.5px;` on `body` fixes this problem.

![screenshot](https://user-images.githubusercontent.com/384997/42453628-9bcea770-838d-11e8-90a6-ef67b2a1deda.png)

**Comment by tombh** [comment]
That's interesting. And thanks for the fix. So I assume I can fix this by detecting `devicePixelRatio` and doing some maths to set the correct padding. I'm gonna have to look into it.

**Comment by niutech** [comment]
I think I found the real issue: on Windows 10 `font-family: monospace` is using Consolas font, which is shorter than Courier New. So the device-ratio-agnostic solution is to use `font-family: 'Courier New', monospace` instead.
