### ISSUE TITLE
is there anything that support the claim less bandwidth

### ISSUE THREAD

**Issue by FERMAT1991** [browsh-org/browsh#72]
Hi, I am just curious and I want to know how much bandwidth it consumes and is there a way for me to know.
I hope you will improve this especially with youtube in my country Morocco if me and my two brothers and sister watching youtube, videos take time to load and with poor quality(this happen with all modern browsers).
thanks so much and I am sorry if I post this as an issue.

**Comment by tobimensch** [comment]
I think for watching videos isn't the right choice. (look into youtube-dl for an alternative)

As for saving bandwidth on regular websites I can confirm that helps a lot. It can load pages in seconds on an extremely low bandwidth connection, where you'd normally wait for minutes or even get a timeout.

It's a game changer for people stuck bad internet in my opinion.

**Comment by tombh** [comment]
I haven't explained it properly in the documentation. But Browsh should be run on a remote server and then accessed through either SSH/Mosh or the HTTP service. That way the remote server downloads the original site's bandwidth and you only need to download the text, on average this creates a saving between 10 to 100 times less data. Unfortunately though video sound doesn't get sent over an SSH connection :(

**Comment by moderation** [comment]
@tombh There are some removed from master documentation hints on how to run in a Docker container with the correct ports exposed at https://github.com/browsh-org/browsh/commit/287d21916d5ec8c1284fe0e3a1687e3dedc54d2e.
The documentation would definitely benefit with a "how to" on setting up a server instance exposing SSH / Mosh. I can't work out how or if port 7777 can be exposed.

**Comment by tombh** [comment]
You're absolutely right. I'm sorry that I never thought to include it in the docs, seeing that's it's such an essential asset to Browsh.

**Comment by FERMAT1991** [comment]
thank you very much you were very helpful.
I wish you all the best.

**Comment by tombh** [comment]
I've added the docs now: https://www.brow.sh/docs/mosh/
