### ISSUE TITLE
Mosh doesn't support true color unless you build it yourself

### ISSUE THREAD

**Issue by michaelnew** [browsh-org/browsh#74]
This isn't a bug with browsh per-se, but since the docs recommend using mosh over ssh I think it's worth updating the readme until there's a new release of mosh. You can use browsh in monochrome mode over mosh, but otherwise everything is completely garbled if you're using the 1.3.2 release.

True color support landed with [this commit](
https://github.com/mobile-shell/mosh/pull/939/commits/ac0492cb5a703ae979b5c923182671d2688b025a), and even though it was 9 months ago they still haven't cut a new release yet. It sounds like they will soon, but until then you have to build from master to get true color.

**Comment by tombh** [comment]
Ah yes, you're absolutely right, I will add that to the docs, thanks.

**Comment by tombh** [comment]
Added to the docs: https://www.brow.sh/docs/mosh/
