### ISSUE TITLE
Is this the expected behave?

### ISSUE THREAD

**Issue by Sraw** [browsh-org/browsh#82]
![image](https://user-images.githubusercontent.com/15711730/42499357-220a0432-8461-11e8-84ed-773446252137.png)

The above is what I get when I `ssh brow.sh`, it seems very different from the video. Is this the expected behave?

I'm on ubuntu 16.04 with terminator.

**Comment by tobimensch** [comment]
Try a different terminal such as konsole. Try it with the latest version of mosh compiled from git.

**Comment by tobimensch** [comment]
I agree that it should eventually work in all terminals.

However in the meantime using other terminals with the true color support required by browsh is the solution.

**Comment by ikari-pl** [comment]
The same problem under iTerm on a mac

**Comment by tombh** [comment]
Yeah, as @tobimensch says. Supporting non true colour terminals would be a nice to have, but it's not currently a priority. At the very least you can always toggle monochrome mode `ALT+m`, which will remove the banding artefacts.

**Comment by changephilip** [comment]
I reproduce this error while using mosh(installed through package manager,debian9 or ubuntu18) to login my remote server.
If you use ssh then it works well.
Then  I build mosh from source code on my remote server and my local machine and doesn't work as well.
Finally I build mosh from git and there is no error now.
