### ISSUE TITLE
(Suggestion) Port to Android?

### ISSUE THREAD

**Issue by JLIT0** [browsh-org/browsh#90]
A text based browser for mobile devices could be very useful, given the limited data allowances on many tariffs, or slow internet in areas with poor signal.

**Comment by tobimensch** [comment]
Dedicated clients for different platforms would be great. Browsh would need a special protocol to be optimized for such use. This is why people should think about donating to @tombh as stuff like this is going to be a lot of work.

**Comment by knyzorg** [comment]
Doesn't any off-the-shelf terminal emulator on android work?

I haven't tried, but I would expect so.

**Comment by parkerlreed** [comment]
Termux should be a good candidate also.

**Comment by tombh** [comment]
Reddit's u/dualfoothands has connected to Browsh using Termux over SSH: https://imgur.com/mBZ7xDa

I need to make it clearer on the home page that Browsh is mainly supposed to be run on a remote server. There are no bandwidth gains to be had by running Browsh on a local device.

Also note that Termux supports Mosh, and that there are other Mosh clients for Android.

Though note that the `ssh brow.sh` demo server doesn't currently support Mosh.
