### ISSUE TITLE
UTF-8 characters input broken

### ISSUE THREAD

**Issue by georgy7** [browsh-org/browsh#93]
Both with docker and with deb-package installation.

```
$ echo $LANG
ru_RU.UTF-8
```

Typing "привет":

![screenshot_20180710_160919](https://user-images.githubusercontent.com/564471/42511829-a2257ca6-845b-11e8-9045-7d2636158ec5.png)

Ubuntu 16.04 (Terminal emulator: Konsole)

**Comment by E100Beta** [comment]
Same here on Gentoo. Unicode that is not in input field displayed fine, but as soon as I tried inputting russian symbols in input field it started acting weird. Inputtin `°` crashed the browser.

**Comment by tombh** [comment]
Fixed. Watch out for the next version release for updated binaries.
