### ISSUE TITLE
multi-browsh? - not sure what to call this haha

### ISSUE THREAD

**Issue by skibz** [browsh-org/browsh#95]
![screen shot 2018-07-10 at 17 20 04](https://user-images.githubusercontent.com/2462211/42520007-8a2280d6-8465-11e8-8c8d-9bd0a11a58bb.png)

i don't know whether this could be abused, or whether it is actually an intended behaviour.

**Comment by parkerlreed** [comment]
Browsheption

**Comment by tombh** [comment]
Nice ;)

This sort of thing was actually causing some serious load spikes on the cluster! I've just deployed a fix now though.
