### ISSUE TITLE
Cannot connect to brow.sh using Mosh for Chrome

### ISSUE THREAD

**Issue by niutech** [browsh-org/browsh#96]
This is what I get when I try to connect to brow.sh using [Mosh for Chrome](https://chrome.google.com/webstore/detail/mosh/ooiklbnjmhbcgemelgfhaeaocllobloj):

> Could NOT authenticate DNS lookup.
> Remote ssh host name/address:
>   brow.sh:22
> ssh-rsa key fingerprint of remote ssh host (MD5):
>   4c:88:19:a2:3a:38:a7:e0:1a:7f:fa:3a:99:95:48:37
> Server fingerprint unknown. Store and continue? (Yes/No): Yes
> Authentication types supported by server:
> Failed to get authentication types: 
> 
> SSH Login failed.

There should be at least a dummy password fallback.

**Comment by parkerlreed** [comment]
The SSH service is only intended to be a demo

````
Live SSH Demo
Just point your SSH client to brow.sh, eg; `ssh brow.sh`. No auth needed. The service is for demonstration only, sessions last 5 minutes and are logged.
Note that SSH is actually a very inefficient protocol, for best results install Browsh on your own server along with Mosh.
````

Also it appears Mosh fro Chrome needs Mosh... Which the demo text explicitly states isn't supported on the demo.

**Comment by tombh** [comment]
As @parkerlreed says, the demo doesn't support Mosh, not because I don't want to but because it's actually really hard to load balance. But I'm in discussion with the Mosh devs and we've got some ideas.

Meanwhile you can of course just install Mosh and Browsh on your own server.
