### ISSUE TITLE
Weird colors over mosh? Need to use bleeding edge mosh

### ISSUE THREAD

**Issue by herohamp** [browsh-org/browsh#98]
https://i.imgur.com/9ljUgVd.png Local
https://i.imgur.com/rYRfHJx.png Over Mosh to server
I was loading speedtest.net in both, and I had nothing different

**Comment by afoster** [comment]
The comments in possible duplicate #77 suggests building the latest mosh from git

**Comment by tombh** [comment]
Ah, damn, again this is my fault for not mentioning in the docs that you need to build the latest version of Mosh to get true colour support. Sorry for not mentioning that :/

**Comment by tombh** [comment]
I've updated the documentation: https://www.brow.sh/docs/mosh/
